const { chromium } = require('playwright');
const fs=require('fs'), path=require('path');
const OUT='/home/bhumukul-raj/Music/nestlacer-test-output/reports/P07/finder'; fs.mkdirSync(OUT,{recursive:true});
const APP='https://app.nestlancer.com'; const PW='Brick2@Build';
const accounts=['arjun.mehta@nestlancer.com','samira.patel@nestlancer.com','rahul.desai@nestlancer.com','ananya.iyer@nestlancer.com','priya.nair@nestlancer.com','vikram.shah@nestlancer.com','kavya.reddy@nestlancer.com','rajan-kumar@nestlancer.com','divya.sharma@nestlancer.com','amit.verma@nestlancer.com','neha.gupta@nestlancer.com','suresh.iyer@nestlancer.com','pooja.kulkarni@nestlancer.com','karthik.menon@nestlancer.com','sandeep.chopra@nestlancer.com'];
function redact(s){return String(s||'').replace(/([A-Za-z0-9._%+-]+)@nestlancer\.com/g,'<demo-email>@nestlancer.com').replaceAll(PW,'<redacted>')}
async function dismiss(p){for(const t of ['Accept','Dismiss'])try{const b=p.getByRole('button',{name:t}).first(); if(await b.isVisible({timeout:500})) await b.click()}catch{}}
async function loginAndQuotes(browser,email){const ctx=await browser.newContext({viewport:{width:1280,height:850},ignoreHTTPSErrors:true}); const p=await ctx.newPage(); const net=[]; p.on('response',res=>{let u=res.url(); if(/quotes|auth\/login|users\/profile/.test(u)) net.push({method:res.request().method(),status:res.status(),url:u.replace(/token=[^&]+/,'token=<redacted>')});}); try{await p.goto(APP+'/login',{waitUntil:'networkidle',timeout:60000}); await dismiss(p); await p.locator('input[type=email],input[name=email]').first().fill(email); await p.locator('input[type=password],input[name=password]').first().fill(PW); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:18000}),p.locator('button[type=submit]').first().click()]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await p.goto(APP+'/quotes',{waitUntil:'networkidle',timeout:60000}); await p.waitForTimeout(1500); const title=await p.title(); const txt=redact(await p.locator('body').innerText().catch(()=>'')); const safe=email.split('@')[0].replace(/[^a-z0-9]+/gi,'_'); await p.screenshot({path:path.join(OUT,safe+'.png'),fullPage:true}).catch(()=>{}); fs.writeFileSync(path.join(OUT,safe+'.txt'),`EMAIL ${email}\nURL ${p.url()}\nTITLE ${title}\n\n${txt}`); const hrefs=await p.evaluate(()=>[...document.querySelectorAll('a[href]')].map(a=>({text:a.textContent.trim(),href:a.href})).filter(a=>a.href.includes('/quotes'))); await ctx.close(); return {email, url:p.url(), title, sample:txt.slice(0,1500), hrefs, net}; }catch(e){await ctx.close().catch(()=>{}); return {email,error:e.message,net};}}
(async()=>{const browser=await chromium.launch({ channel: 'chrome', headless: true}); const results=[]; for(const a of accounts){console.log('checking',a); const r=await loginAndQuotes(browser,a); results.push(r); console.log(a, r.error||r.title, (r.sample||'').slice(0,200).replace(/\n/g,' | '));} await browser.close(); fs.writeFileSync(path.join(OUT,'results.json'),JSON.stringify(results,null,2));})();
