const { chromium } = require('playwright');
const fs=require('fs'), path=require('path');
const OUT='/home/bhumukul-raj/Music/nestlacer-test-output/reports/P10/finder'; fs.mkdirSync(OUT,{recursive:true});
const APP='https://app.nestlancer.com'; const PW='Brick2@Build';
const accounts=['arjun.mehta@nestlancer.com','samira.patel@nestlancer.com','rahul.desai@nestlancer.com','ananya.iyer@nestlancer.com','priya.nair@nestlancer.com','vikram.shah@nestlancer.com','kavya.reddy@nestlancer.com','divya.sharma@nestlancer.com','amit.verma@nestlancer.com','neha.gupta@nestlancer.com','suresh.iyer@nestlancer.com','pooja.kulkarni@nestlancer.com','karthik.menon@nestlancer.com','sandeep.chopra@nestlancer.com'];
function redact(s){return String(s||'').replace(/([A-Za-z0-9._%+-]+)@nestlancer\.com/g,'<demo-email>@nestlancer.com').replaceAll(PW,'<redacted>')}
async function dismiss(p){for(const t of ['Accept','Dismiss'])try{const b=p.getByRole('button',{name:t}).first(); if(await b.isVisible({timeout:500})) await b.click()}catch{}}
async function login(ctx,email){const p=await ctx.newPage(); await p.goto(APP+'/login',{waitUntil:'networkidle',timeout:60000}); await dismiss(p); await p.locator('input[type=email],input[name=email]').first().fill(email); await p.locator('input[type=password],input[name=password]').first().fill(PW); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:18000}),p.locator('button[type=submit]').first().click()]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); return p;}
(async()=>{const browser=await chromium.launch({ channel: 'chrome', headless: true}); const results=[]; for(const email of accounts){console.log('acct',email); const ctx=await browser.newContext({viewport:{width:1280,height:850},ignoreHTTPSErrors:true}); try{const p=await login(ctx,email); await p.goto(APP+'/projects',{waitUntil:'networkidle',timeout:60000}); await p.waitForTimeout(1000); const projects=await p.evaluate(()=>[...document.querySelectorAll('a[href*="/projects/"]')].map(a=>({text:a.textContent.trim(),href:a.href}))); const acct={email, projects:[]}; for(const proj of projects.slice(0,5)){const pid=proj.href.split('/projects/')[1]?.split(/[?#]/)[0]; const rec={projectText:proj.text, href:proj.href, id:pid}; for(const tab of ['deliverables','files']){await p.goto(`${APP}/projects/${pid}?tab=${tab}`,{waitUntil:'networkidle',timeout:60000}); await p.waitForTimeout(1000); const text=redact(await p.locator('body').innerText().catch(()=>'')); const controls=await p.evaluate(()=>({buttons:[...document.querySelectorAll('button')].map(b=>b.textContent.trim()).filter(Boolean), links:[...document.querySelectorAll('a[href]')].map(a=>({text:a.textContent.trim(),href:a.href})), inputs:[...document.querySelectorAll('input,textarea,select')].map(e=>({tag:e.tagName,type:e.getAttribute('type'),name:e.getAttribute('name'),placeholder:e.getAttribute('placeholder')}))})).catch(e=>({error:e.message})); rec[tab]={text:text.slice(0,4000), controls}; }
acct.projects.push(rec);} results.push(acct); const safe=email.split('@')[0].replace(/[^a-z0-9]+/gi,'_'); fs.writeFileSync(path.join(OUT,safe+'.json'),JSON.stringify(acct,null,2)); await ctx.close();}catch(e){results.push({email,error:e.message}); await ctx.close().catch(()=>{});} } await browser.close(); fs.writeFileSync(path.join(OUT,'results.json'),JSON.stringify(results,null,2));})();
