const { chromium } = require('playwright');
const fs=require('fs'); const path=require('path');
const OUT=path.join(__dirname, '..', 'nestlancer-test-output', 'reports', 'P12', 'finder'); fs.mkdirSync(OUT,{recursive:true});
const APP='https://app.nestlancer.com'; const PW='Brick2@Build';
const accounts=['arjun.mehta','samira.patel','rahul.desai','ananya.iyer','priya.nair','vikram.shah','kavya.reddy','rajan.kumar','divya.sharma','amit.verma','neha.gupta','suresh.iyer','pooja.kulkarni','karthik.menon','sandeep.chopra'].map(x=>`${x}@nestlancer.com`);
async function login(page,email){await page.goto(APP+'/login',{waitUntil:'domcontentloaded'});await page.locator('input[type="email"],input[name="email"]').first().fill(email);await page.locator('input[type="password"],input[name="password"]').first().fill(PW);await Promise.allSettled([page.waitForURL(u=>!u.pathname.includes('/login'),{timeout:20000}),page.locator('button[type="submit"]').first().click()]);await page.waitForLoadState('networkidle',{timeout:8000}).catch(()=>{});}
(async()=>{const browser=await chromium.launch({ headless: true}); const rows=[]; for(const email of accounts){const ctx=await browser.newContext({viewport:{width:1280,height:850},ignoreHTTPSErrors:true}); const page=await ctx.newPage(); try{await login(page,email); await page.goto(APP+'/payments',{waitUntil:'domcontentloaded',timeout:45000}); await page.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await page.screenshot({path:path.join(OUT,email.split('@')[0].replace('.','_')+'.png'),fullPage:true}).catch(()=>{}); const text=await page.locator('body').innerText({timeout:5000}).catch(e=>'ERR '+e.message); let api=null; try{api=await page.evaluate(async()=>{const r=await fetch('/api/v1/payments?page=1&limit=100',{credentials:'include'}); return {status:r.status,body:await r.json().catch(()=>null)};});}catch(e){api={error:e.message};}
 fs.writeFileSync(path.join(OUT,email.split('@')[0].replace('.','_')+'.txt'),text); fs.writeFileSync(path.join(OUT,email.split('@')[0].replace('.','_')+'.json'),JSON.stringify(api,null,2));
 const items=api?.body?.payments||api?.body?.data||api?.body?.items||api?.body?.results||[]; if(Array.isArray(items)){for(const it of items){rows.push({email,id:it.id||it.paymentId||it.uuid,amount:it.amount||it.total||it.amountInCents,currency:it.currency,status:it.status,project:it.project?.title||it.projectTitle||it.project?.name||it.projectName,milestone:it.milestone?.title||it.milestoneTitle,invoiceNumber:it.invoiceNumber||it.invoice?.number,createdAt:it.createdAt,keys:Object.keys(it)});} } else rows.push({email,unparsed:true,api});
 }catch(e){rows.push({email,error:e.message});} await ctx.close().catch(()=>{});} await browser.close(); fs.writeFileSync(path.join(OUT,'payment_rows.json'),JSON.stringify(rows,null,2)); console.log(JSON.stringify(rows.map(r=>({email:r.email,id:r.id,amount:r.amount,status:r.status,project:r.project,invoiceNumber:r.invoiceNumber,error:r.error,unparsed:r.unparsed})),null,2));})();
