const { chromium }=require('playwright');
const fs=require('fs'); const path=require('path'); const crypto=require('crypto'); const {execFileSync}=require('child_process');
const OUT='/home/bhumukul-raj/Music/nestlacer-test-output/reports/P15'; const EVID=path.join(OUT,'evidence_2fa'); fs.mkdirSync(EVID,{recursive:true}); const APP='https://app.nestlancer.com';
const runId=Date.now().toString(36)+'-'+crypto.randomBytes(3).toString('hex'); let email='', token=''; const pass='AuditP15TwoFA!'+crypto.randomBytes(5).toString('hex')+'aA1';
function sanitizeUrl(u){try{const url=new URL(u); for(const k of [...url.searchParams.keys()]) if(/token|code|otp|password|secret|signature|key|auth|session|cookie|credential|expires|signed|x-amz|t/i.test(k)) url.searchParams.set(k,'<redacted>'); return url.toString();}catch{return String(u||'')}}
function redact(s){let v=String(s??''); for(const x of [email,token,pass].filter(Boolean)) v=v.split(x).join(x.includes('@')?'<audit-p15-2fa-mail>@<mail-domain>':'<redacted-secret>'); return v.replace(/audit-p15-2fa-[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+/gi,'<audit-p15-2fa-mail>@<mail-domain>').replace(/([A-Za-z0-9._%+-]+)@nestlancer\.com/g,'<demo-email>@nestlancer.com').replace(/token=[^\s&"'<>]+/gi,'token=<redacted>').replace(/(token|otp|code|secret|password|signature|cookie|authorization|credential|backup)(["'\s:=]+)([^\s"'<>]+)/gi,'$1$2<redacted>').replace(/\b[A-Z2-7]{16,}\b/g,'<redacted-base32-secret>').replace(/\b\d{6}\b/g,'<redacted-6digit-code>').replace(/eyJ[A-Za-z0-9._-]+/g,'<redacted-jwt>').slice(0,22000)}
async function dismiss(p){for(const t of ['Accept','Dismiss']){try{const b=p.getByRole('button',{name:t}).first(); if(await b.isVisible({timeout:700})) await b.click()}catch{}}}
async function snap(p,slug,result,extra={}){await p.waitForTimeout(700); await p.screenshot({path:path.join(EVID,slug+'.png'),fullPage:true}).catch(()=>{}); const text=redact(await p.locator('body').innerText().catch(()=>'')); const url=sanitizeUrl(p.url()); const title=await p.title().catch(()=> ''); fs.writeFileSync(path.join(EVID,slug+'.txt'),`URL: ${url}\nTITLE: ${title}\n\n${text}`); result.steps.push({slug,url,title,...extra}); return {text,url,title};}
async function makeMailbox(){const d=await (await fetch('https://api.mail.tm/domains')).json(); const domain=d['hydra:member'][0].domain; email=`audit-p15-2fa-${runId}@${domain}`.toLowerCase(); let r=await fetch('https://api.mail.tm/accounts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address:email,password:pass})}); if(!r.ok&&r.status!==422) throw Error('mail create '+r.status); r=await fetch('https://api.mail.tm/token',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address:email,password:pass})}); const j=await r.json(); token=j.token; return {address:email,token};}
async function poll(m,ms=50000){const end=Date.now()+ms; while(Date.now()<end){const j=await (await fetch('https://api.mail.tm/messages',{headers:{authorization:`Bearer ${m.token}`}})).json(); const msg=(j['hydra:member']||[])[0]; if(msg){const full=await (await fetch('https://api.mail.tm/messages/'+msg.id,{headers:{authorization:`Bearer ${m.token}`}})).json(); const src=[full.text,full.html,full.intro].flat().filter(Boolean).join('\n'); return [...src.matchAll(/https?:\/\/[^\s"'<>]+/g)].map(x=>x[0].replace(/&amp;/g,'&').replace(/[\])}.,;]+$/,'')).find(u=>/verify-email\?token=/.test(u));} await new Promise(r=>setTimeout(r,2500));} return null;}
async function login(p){await p.goto(APP+'/login',{waitUntil:'domcontentloaded'}); await dismiss(p); await p.locator('input[type=email],input[name=email]').first().fill(email); await p.locator('input[type=password],input[name=password]').first().fill(pass); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:25000}),p.locator('form').first().getByRole('button',{name:/^sign in$/i}).click({timeout:6000})]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await p.waitForTimeout(1000); if(p.url().includes('/login')){await p.goto(APP+'/dashboard',{waitUntil:'domcontentloaded'}).catch(()=>{}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{});} return !p.url().includes('/login');}
function totp(secret){try{return execFileSync('python3',['-c',`import pyotp; print(pyotp.TOTP(${JSON.stringify(secret)}).now())`],{encoding:'utf8'}).trim()}catch{return null}}
async function fillAny(p,sels,val){for(const s of sels){const loc=p.locator(s).first(); if(await loc.count().catch(()=>0)){try{await loc.fill(val,{timeout:1500}); return s}catch{}}} return null}
async function clickButton(p,re){try{await p.getByRole('button',{name:re}).first().click({timeout:4000}); return true}catch{} try{await p.locator('button').filter({hasText:re}).first().click({timeout:4000}); return true}catch{} return false}
(async()=>{const result={generatedAt:new Date().toISOString(),steps:[],verdict:'UNKNOWN',blockers:[],bugs:[]}; const browser=await chromium.launch({ channel: 'chrome', headless: true}); const ctx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const p=await ctx.newPage();
try{const m=await makeMailbox(); await p.goto(APP+'/register',{waitUntil:'domcontentloaded'}); await dismiss(p); await p.locator('input[name=firstName]').fill('Audit'); await p.locator('input[name=lastName]').fill('P15TwoFA'); await p.locator('input[name=email]').fill(email); await p.locator('input[name=password]').fill(pass); await p.locator('input[name=confirmPassword]').fill(pass); await p.locator('input[name=acceptTerms]').check(); await p.locator('button[type=submit]').click(); await p.waitForTimeout(3000); await snap(p,'register_2fa_audit',result); const link=await poll(m); fs.writeFileSync(path.join(EVID,'verify_link_redacted.txt'),redact(link?sanitizeUrl(link):'NO LINK')); if(!link) throw Error('no verify link'); await p.goto(link,{waitUntil:'networkidle'}); await snap(p,'verify_2fa_audit',result); const ok=await login(p); await snap(p,'login_2fa_audit',result,{loginOk:ok}); if(!ok) throw Error('login failed'); await p.goto(APP+'/settings/security',{waitUntil:'domcontentloaded'}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'security_before_2fa',result); await fillAny(p,['#security-2fa-password','input[name=twoFactorPassword]'],pass); await clickButton(p,/Start 2FA setup/i); await p.waitForTimeout(3500); await snap(p,'twofa_setup_started',result); const raw=await p.evaluate(()=>document.body.innerText+'\n'+[...document.querySelectorAll('img,a,svg,canvas')].map(e=>[e.getAttribute('src'),e.getAttribute('href'),e.getAttribute('alt'),e.getAttribute('data-uri'),e.getAttribute('data-secret')].filter(Boolean).join(' ')).join('\n')).catch(()=> ''); let secret=null; const uri=raw.match(/otpauth:\/\/totp\/[^\s"'<>]+/i); if(uri){try{secret=new URL(uri[0]).searchParams.get('secret')}catch{}} if(!secret){const ms=raw.match(/\b[A-Z2-7]{16,}\b/g)||[]; secret=ms[0];}
 if(!secret){result.verdict='BLOCKED_NO_SECRET'; result.blockers.push('No manual TOTP secret/otpauth found after setup start');}
 else {await fillAny(p,['#security-2fa-code','input[name=twoFactorCode]','input[autocomplete=one-time-code]'],'000000'); await clickButton(p,/Verify and enable|Verify|Enable/i); await p.waitForTimeout(2500); await snap(p,'twofa_wrong_code_result',result); const code=totp(secret); await fillAny(p,['#security-2fa-password','input[name=twoFactorPassword]'],pass).catch(()=>{}); await fillAny(p,['#security-2fa-code','input[name=twoFactorCode]','input[autocomplete=one-time-code]'],code); await clickButton(p,/Verify and enable|Verify|Enable/i); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await p.waitForTimeout(3500); const final=await snap(p,'twofa_valid_code_result',result); const enabled=/enabled|backup codes|disable|two-factor authentication\s+enabled/i.test(final.text)&&!/invalid|failed|error/i.test(final.text); result.verdict=enabled?'PASS_ENABLED':'FAIL_VALID_TOTP_NOT_ENABLED'; if(!enabled) result.bugs.push({id:'NL-BUG-P15-2FA-1',severity:'P1',title:'Valid TOTP did not clearly enable 2FA',evidence:'evidence_2fa/twofa_valid_code_result'}); if(enabled){await p.goto(APP+'/settings/security',{waitUntil:'domcontentloaded'}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); const reload=await snap(p,'twofa_after_reload',result); if(/backup code/i.test(reload.text)) result.bugs.push({id:'NL-BUG-P15-2FA-2',severity:'P2',title:'Backup codes visible after reload',evidence:'evidence_2fa/twofa_after_reload'}); try{await fillAny(p,['#security-2fa-password','input[name=twoFactorPassword]'],pass); await clickButton(p,/Disable 2FA|Disable two-factor|Turn off/i); await p.waitForTimeout(2500); await snap(p,'twofa_disable_attempt',result)}catch{}} }
}catch(e){result.blockers.push(redact(e.message)); if(result.verdict==='UNKNOWN') result.verdict='ERROR';} await ctx.close(); await browser.close(); fs.writeFileSync(path.join(OUT,'p15_2fa_supplement.json'),JSON.stringify(result,null,2)); console.log(JSON.stringify({verdict:result.verdict,bugs:result.bugs,blockers:result.blockers},null,2));})();
