const { chromium } = require('playwright');
const fs=require('fs'); const path=require('path');
const OUT=path.join(__dirname, '..', 'nestlancer-test-output', 'reports', 'P23'); const EVID=path.join(OUT,'evidence_supplement'); fs.mkdirSync(EVID,{recursive:true});
const APP='https://app.nestlancer.com', ADMIN='https://admin.nestlancer.com';
const PASS='Brick2@Build', ARJUN='arjun.mehta@nestlancer.com', ADMIN_EMAIL='admin@nestlancer.com';
const RUN='AUDIT-P23-SUPP-20261005-'+Date.now().toString(36).slice(-4);
function sanitizeUrl(u){try{const x=new URL(u); for(const k of [...x.searchParams.keys()]) if(/token|secret|signature|code|otp|password|cookie|auth|x-amz|t/i.test(k)) x.searchParams.set(k,'<redacted>'); return x.toString()}catch{return String(u||'')}}
function redact(s){return String(s??'').replaceAll(PASS,'<redacted-demo-password>').replace(/([A-Za-z0-9._%+-]+)@nestlancer\.com/g,'<demo-email>@nestlancer.com').replace(/eyJ[A-Za-z0-9._-]+/g,'<redacted-jwt>').replace(/https:\/\/s3\.nestlancer\.com\/[^\s"'<>]+/gi,'https://s3.nestlancer.com/<signed-url-redacted>').replace(/(token|otp|code|secret|password|signature|cookie|authorization)(["'\s:=]+)([^\s"'<>]+)/gi,'$1$2<redacted>').slice(0,25000)}
async function attach(p,res,label){const started=new Map(); p.on('request',r=>started.set(r,Date.now())); p.on('response',async r=>{const req=r.request(); let u=sanitizeUrl(r.url()); if(!/nestlancer\.com/.test(u))return; if(!(req.resourceType()==='document'||/\/api\//.test(u)||/quote|request|template|prefill|schedule/i.test(u)))return; let keys=[]; if(req.postData()){try{keys=Object.keys(JSON.parse(req.postData()))}catch{keys=['<non-json>']}} res.network.push({label,method:req.method(),path:(()=>{try{const uu=new URL(u);return uu.pathname+uu.search}catch{return u}})(),status:r.status(),keys,ms:started.has(req)?Date.now()-started.get(req):null}); try{ if(req.method()==='POST' && /\/api\/v1\/admin\/requests\/[^/]+\/quotes$/.test(new URL(r.url()).pathname)){ const j=await r.json(); if(j?.data?.id) res.quoteId=j.data.id; } }catch{}}); p.on('console',m=>{if(['error','warning'].includes(m.type()))res.console.push({label,type:m.type(),text:redact(m.text())})})}
async function dismiss(p){for(const name of ['Accept','Dismiss']){try{const b=p.getByRole('button',{name}).first(); if(await b.isVisible({timeout:500})) await b.click({timeout:1000});}catch{}}}
async function snap(p,slug,res,extra={}){await p.waitForTimeout(650).catch(()=>{}); const png=path.join(EVID,slug+'.png'); await p.screenshot({path:png,fullPage:true}).catch(()=>{}); const text=redact(await p.locator('body').innerText({timeout:5000}).catch(e=>'ERR '+e.message)); fs.writeFileSync(path.join(EVID,slug+'.txt'),`URL: ${sanitizeUrl(p.url())}\nTITLE: ${await p.title().catch(()=> '')}\n\n${text}`); const controls=await p.evaluate(()=>({buttons:[...document.querySelectorAll('button,[role=button]')].map((b,i)=>({i,text:(b.textContent||b.getAttribute('aria-label')||'').trim().slice(0,120),disabled:b.disabled||b.getAttribute('aria-disabled')==='true',aria:b.getAttribute('aria-label')})).slice(0,220),inputs:[...document.querySelectorAll('input,textarea,select')].map((el,i)=>({i,tag:el.tagName,type:el.getAttribute('type')||el.type,name:el.getAttribute('name'),placeholder:el.getAttribute('placeholder'),id:el.id,value:(el.value||'').slice(0,80),checked:el.checked})).slice(0,180),dialogs:[...document.querySelectorAll('[role=dialog],dialog,[data-radix-popper-content-wrapper]')].map((d,i)=>({i,text:(d.textContent||'').trim().slice(0,500)}))})).catch(e=>({error:e.message})); res.snaps.push({slug,url:sanitizeUrl(p.url()),title:await p.title().catch(()=>''),png:path.relative(OUT,png),extra,controls}); return {text,controls};}
async function clientLogin(browser,res){const ctx=await browser.newContext({viewport:{width:1365,height:900},acceptDownloads:true,ignoreHTTPSErrors:true}); const p=await ctx.newPage(); await attach(p,res,'client'); await p.goto(APP+'/login',{waitUntil:'domcontentloaded'}); await dismiss(p); await p.locator('input[type=email]').fill(ARJUN); await p.locator('input[type=password]').fill(PASS); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:25000}),p.getByRole('button',{name:/sign in/i}).click()]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'supp_client_login_after',res); return {ctx,p};}
async function adminLogin(browser,res){const ctx=await browser.newContext({viewport:{width:1365,height:900},acceptDownloads:true,ignoreHTTPSErrors:true}); const p=await ctx.newPage(); await attach(p,res,'admin'); await p.goto(ADMIN+'/login',{waitUntil:'domcontentloaded'}); await dismiss(p); await p.locator('input[type=email]').fill(ADMIN_EMAIL); await p.locator('input[type=password]').fill(PASS); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:25000}),p.getByRole('button',{name:/Enter console|sign in|log in/i}).click()]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'supp_admin_login_after',res); return {ctx,p};}
async function tryClick(p,res,name,re,slug){const rec={name,slug,clicked:false}; try{const b=p.getByRole('button',{name:re}).first(); if(await b.count()){await b.click({timeout:5000}); rec.clicked=true; await p.waitForLoadState('networkidle',{timeout:6000}).catch(()=>{}); await snap(p,slug,res,{control:name,clicked:true}); try{await p.keyboard.press('Escape'); await p.waitForTimeout(300);}catch{}} else {await snap(p,slug+'_missing',res,{control:name,clicked:false});}}catch(e){rec.error=e.message; await snap(p,slug+'_error',res,{control:name,error:e.message}).catch(()=>{});} res.controls.push(rec); return rec;}
(async()=>{const res={runId:RUN,requestId:null,quoteId:null,network:[],console:[],snaps:[],controls:[],storage:{},findings:[],notes:[]}; const browser=await chromium.launch({ headless: true});
 const c=await clientLogin(browser,res); const p=c.p; await p.goto(APP+'/requests/new',{waitUntil:'domcontentloaded'}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'supp_client_request_new',res); await p.locator('#req-title').fill(RUN+' Request'); await p.locator('#req-description').fill('P23 supplement audit request for quote builder template, duplicate, add/remove, schedule, and browser-back coverage.'); await p.locator('#req-budget-min').fill('1000'); await p.locator('#req-budget-max').fill('5000'); await p.locator('#req-requirements').fill('Template and prefill coverage\nDuplicate and reorder coverage\nPayment schedule edge coverage'); await Promise.allSettled([p.waitForURL(u=>u.pathname!='/requests/new',{timeout:25000}),p.getByRole('button',{name:/Save draft/i}).click()]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'supp_client_request_draft',res); res.requestId=(new URL(p.url()).pathname.match(/requests\/([^/]+)/)||[])[1]; try{await p.getByRole('button',{name:/Submit for review/i}).click({timeout:6000}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'supp_client_request_submitted',res);}catch(e){res.notes.push('submit failed '+e.message)} await c.ctx.close();
 const a=await adminLogin(browser,res); const ap=a.p; if(!res.requestId) throw new Error('no request id'); await ap.goto(`${ADMIN}/requests/${res.requestId}/quote/new`,{waitUntil:'domcontentloaded'}); await ap.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(ap,'supp_builder_initial',res);
 // Storage/cookie metadata only, no values.
 res.storage=await ap.evaluate(()=>({localStorageKeys:Object.keys(localStorage),sessionStorageKeys:Object.keys(sessionStorage)})).catch(e=>({error:e.message})); res.storage.cookies=(await a.ctx.cookies()).map(c=>({name:c.name,domain:c.domain,path:c.path,expires:c.expires,secure:c.secure,httpOnly:c.httpOnly,sameSite:c.sameSite}));
 await tryClick(ap,res,'Apply phase template',/Apply phase template/i,'supp_apply_phase_template');
 await tryClick(ap,res,'Line-item library',/Line-item library/i,'supp_line_item_library');
 await tryClick(ap,res,'Copy from past quote',/Copy from past quote/i,'supp_copy_from_past_quote');
 await tryClick(ap,res,'Load prefill',/Load prefill/i,'supp_load_prefill');
 // Fill huge text safely and exercise add/duplicate/reorder.
 const inputs=ap.locator('input,textarea'); await inputs.nth(1).fill('AUDIT-P23 supplemental phase'); const huge='AUDIT-P23 huge text wrap '+('longword'.repeat(50))+' <script>alert(1)</script> ../etc/passwd'; await inputs.nth(2).fill(huge); await inputs.nth(3).fill('2'); await inputs.nth(4).fill('499'); await snap(ap,'supp_builder_huge_text_priced',res);
 await tryClick(ap,res,'Add line',/Add line to Phase 1/i,'supp_add_line');
 await tryClick(ap,res,'Duplicate phase',/Duplicate phase/i,'supp_duplicate_phase');
 await tryClick(ap,res,'Add phase',/Add phase/i,'supp_add_phase');
 await tryClick(ap,res,'Reorder/down arrow',/^↓$|Move down|down/i,'supp_reorder_down');
 await tryClick(ap,res,'Reorder/up arrow',/^↑$|Move up|up/i,'supp_reorder_up');
 // Payment schedule custom invalid totals.
 await ap.getByRole('button',{name:/Next/i}).click({timeout:5000}); await ap.waitForTimeout(800); await snap(ap,'supp_pricing_initial',res); await tryClick(ap,res,'Custom schedule',/Custom %|Custom/i,'supp_custom_schedule_selected');
 const nums=ap.locator('input[type=number]'); const n=await nums.count().catch(()=>0); if(n>=2){await nums.nth(0).fill('60').catch(()=>{}); await nums.nth(1).fill('60').catch(()=>{}); await snap(ap,'supp_custom_schedule_invalid_120_percent',res,{numberInputs:n});} else {await snap(ap,'supp_custom_schedule_no_number_inputs',res,{numberInputs:n});}
 await tryClick(ap,res,'50/50 preset restore',/50% deposit|Half upfront/i,'supp_restore_5050_preset');
 // Terms and create audit draft; browser back after save checked in editor.
 try{await ap.getByRole('button',{name:/Next/i}).click({timeout:5000}); await ap.waitForTimeout(800); await snap(ap,'supp_terms_page',res); await ap.getByRole('button',{name:/Create quote/i}).click({timeout:8000}); await ap.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await ap.waitForTimeout(1600); await snap(ap,'supp_quote_created_draft',res);}catch(e){res.notes.push('create draft failed '+e.message)}
 if(res.quoteId){await ap.goto(`${ADMIN}/requests/${res.requestId}/quote/edit`,{waitUntil:'domcontentloaded'}); await ap.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(ap,'supp_edit_draft_loaded',res); try{await ap.locator('textarea').first().fill('AUDIT-P23 supplement browser-back-after-save edited line.'); await ap.getByRole('button',{name:/Save changes/i}).click({timeout:6000}); await ap.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(ap,'supp_edit_after_save',res); await ap.goBack({waitUntil:'domcontentloaded',timeout:15000}).catch(e=>res.notes.push('browser back after save error '+e.message)); await ap.waitForLoadState('networkidle',{timeout:8000}).catch(()=>{}); await snap(ap,'supp_browser_back_after_save',res);}catch(e){res.notes.push('edit/back failed '+e.message)}}
 // Source anchor availability audit.
 const anchors=['RequestQuoteBuilderClient.tsx','RequestQuoteEditClient.tsx','AdminCreateQuoteForm.tsx','QuoteLineItemsEditor.tsx','PaymentScheduleSection.tsx'];
 res.sourceAnchorAudit=anchors.map(a=>({anchor:a,found:false,note:'Source tree is not included in prompt repository snapshot; runtime UI/network evidence used instead.'}));
 await a.ctx.close(); await browser.close();
 // Simple leak/XSS observations from evidence text.
 const allText=res.snaps.map(s=>fs.readFileSync(path.join(OUT,s.png.replace(/\.png$/,'.txt')),'utf8')).join('\n');
 res.findings.push({id:'P23-SUPP-PREFILL-LEAK',verdict:/Rahul Desai|Karthik|Neha/i.test(allText)?'CHECK_VISIBLE_OTHER_CLIENT_NAMES':'PASS_NO_OTHER_CLIENT_NAME_IN_SUPP_TEXT',evidence:'evidence_supplement/supp_*prefill*'});
 fs.writeFileSync(path.join(OUT,'p23_builder_supplement.json'),JSON.stringify(res,null,2));
 const rows=res.controls.map(c=>`| ${c.name} | ${c.clicked?'Clicked':'Not found/not clicked'} | ${c.error?redact(c.error):'OK'} | ${c.slug} |`).join('\n');
 const net=res.network.map(n=>`| ${n.label} | ${n.method} ${n.path} | ${n.status} | ${(n.keys||[]).join(', ')} | ${n.ms??''}ms |`).join('\n');
 const storageRows=[`| localStorage keys | ${(res.storage.localStorageKeys||[]).join(', ')||'-'} | Values not captured |`,`| sessionStorage keys | ${(res.storage.sessionStorageKeys||[]).join(', ')||'-'} | Values not captured |`].concat((res.storage.cookies||[]).map(c=>`| cookie ${c.name} | domain=${c.domain}; path=${c.path}; secure=${c.secure}; httpOnly=${c.httpOnly}; sameSite=${c.sameSite}; expires=${c.expires} | Value not captured |`)).join('\n');
 const shots=res.snaps.map(s=>`- ${s.slug}: \`${s.png}\` — ${s.title} — ${s.url}`).join('\n');
 const md=`# P23 Supplement — builder controls, prefill/template, schedule and browser-back coverage\n\n- Supplemental audit request: \`${res.requestId||'-'}\`\n- Supplemental draft quote: \`${res.quoteId||'-'}\`\n- Scope: phase template, line-item library, copy/prefill controls, add line, duplicate phase, add/reorder phase, huge text, custom schedule invalid totals, storage metadata, source-anchor availability, browser back after save.\n\n## Controls exercised\n| Control | Result | Error/notes | Evidence |\n|---|---|---|---|\n${rows}\n\n## Storage/cookie metadata captured without values\n| Type | Keys / attributes | Value policy |\n|---|---|---|\n${storageRows}\n\n## Source anchor audit\n| Anchor | Found in prompt repo? | Note |\n|---|---|---|\n${res.sourceAnchorAudit.map(x=>`| ${x.anchor} | ${x.found?'Yes':'No'} | ${x.note} |`).join('\n')}\n\n## Network/API observations\n| Context | Method/path | Status | Request keys | Duration |\n|---|---|---:|---|---:|\n${net}\n\n## Findings\n${res.findings.map(f=>`- ${f.id}: ${f.verdict} (${f.evidence})`).join('\n')||'- None.'}\n\n## Evidence\n${shots}\n`;
 fs.writeFileSync(path.join(OUT,'p23_builder_supplement.md'),md);
})();
