const { chromium } = require('playwright');
const fs=require('fs'), path=require('path');
const OUT=path.join(__dirname, '..', 'nestlancer-test-output', 'reports', 'P23'), EVID=path.join(OUT,'evidence_supplement'); fs.mkdirSync(EVID,{recursive:true});
const ADMIN='https://admin.nestlancer.com', APP='https://app.nestlancer.com'; const PASS='Brick2@Build', ADMIN_EMAIL='admin@nestlancer.com';
const prev=JSON.parse(fs.readFileSync(path.join(OUT,'p23_builder_supplement.json'),'utf8')); const reqId=prev.requestId;
function sanitizeUrl(u){try{const x=new URL(u); for(const k of [...x.searchParams.keys()]) if(/token|secret|signature|code|otp|password|cookie|auth|x-amz|t/i.test(k)) x.searchParams.set(k,'<redacted>'); return x.toString()}catch{return String(u||'')}}
function redact(s){return String(s??'').replaceAll(PASS,'<redacted-demo-password>').replace(/([A-Za-z0-9._%+-]+)@nestlancer\.com/g,'<demo-email>@nestlancer.com').replace(/eyJ[A-Za-z0-9._-]+/g,'<redacted-jwt>').replace(/https:\/\/s3\.nestlancer\.com\/[^\s"'<>]+/gi,'https://s3.nestlancer.com/<signed-url-redacted>').replace(/(token|otp|code|secret|password|signature|cookie|authorization)(["'\s:=]+)([^\s"'<>]+)/gi,'$1$2<redacted>').slice(0,25000)}
async function snap(p,slug,res,extra={}){await p.waitForTimeout(700).catch(()=>{}); const png=path.join(EVID,slug+'.png'); await p.screenshot({path:png,fullPage:true}).catch(()=>{}); const text=redact(await p.locator('body').innerText({timeout:5000}).catch(e=>'ERR '+e.message)); fs.writeFileSync(path.join(EVID,slug+'.txt'),`URL: ${sanitizeUrl(p.url())}\nTITLE: ${await p.title().catch(()=> '')}\n\n${text}`); res.snaps.push({slug,png:path.relative(OUT,png),url:sanitizeUrl(p.url()),title:await p.title().catch(()=> ''),extra}); return text;}
async function attach(p,res){p.on('response',async r=>{const req=r.request(); let u=sanitizeUrl(r.url()); if(!/nestlancer\.com/.test(u))return; if(!(req.resourceType()==='document'||/\/api\//.test(u)||/quote|request/i.test(u)))return; let keys=[]; if(req.postData()){try{keys=Object.keys(JSON.parse(req.postData()))}catch{keys=['<non-json>']}} res.network.push({method:req.method(),path:(()=>{try{const uu=new URL(u);return uu.pathname+uu.search}catch{return u}})(),status:r.status(),keys}); try{ if(req.method()==='POST' && /\/api\/v1\/admin\/requests\/[^/]+\/quotes$/.test(new URL(r.url()).pathname)){const j=await r.json(); if(j?.data?.id) res.quoteId=j.data.id;}}catch{}});}
(async()=>{const res={requestId:reqId,quoteId:null,network:[],snaps:[],notes:[]}; const browser=await chromium.launch({ headless: true}); const ctx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true,acceptDownloads:true}); const p=await ctx.newPage(); await attach(p,res); await p.goto(ADMIN+'/login',{waitUntil:'domcontentloaded'}); await p.locator('input[type=email]').fill(ADMIN_EMAIL); await p.locator('input[type=password]').fill(PASS); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:25000}),p.getByRole('button',{name:/Enter console|sign in|log in/i}).click()]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'supp_back_admin_login_after',res);
 await p.goto(`${ADMIN}/requests/${reqId}/quote/new`,{waitUntil:'domcontentloaded'}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'supp_back_builder_fresh',res);
 const f=p.locator('input,textarea'); await f.nth(1).fill('AUDIT-P23 back-after-save phase'); await f.nth(2).fill('AUDIT-P23 back-after-save minimal line item.'); await f.nth(3).fill('1'); await f.nth(4).fill('1250'); await snap(p,'supp_back_builder_filled',res); await p.getByRole('button',{name:/Next/i}).click({timeout:5000}); await p.waitForTimeout(700); await snap(p,'supp_back_pricing_5050',res); await p.getByRole('button',{name:/Next/i}).click({timeout:5000}); await p.waitForTimeout(700); await snap(p,'supp_back_terms',res); await p.getByRole('button',{name:/Create quote/i}).click({timeout:8000}); await p.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); await p.waitForTimeout(1800); await snap(p,'supp_back_quote_created_draft',res); if(!res.quoteId){const text=await p.locator('body').innerText().catch(()=> ''); const m=text.match(/01a[0-9a-f-]{30,}/i); if(m)res.quoteId=m[0];}
 if(res.quoteId){await p.goto(`${ADMIN}/requests/${reqId}/quote/edit`,{waitUntil:'domcontentloaded'}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'supp_back_edit_loaded',res); await p.locator('textarea').first().fill('AUDIT-P23 browser-back-after-save edited line item.'); await p.getByRole('button',{name:/Save changes/i}).click({timeout:6000}); await p.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); await snap(p,'supp_back_edit_after_save',res); await p.goBack({waitUntil:'domcontentloaded',timeout:15000}).catch(e=>res.notes.push('goBack error '+e.message)); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'supp_back_after_browser_back',res);} else res.notes.push('no quote id, edit/back skipped');
 await ctx.close(); await browser.close(); fs.writeFileSync(path.join(OUT,'p23_back_after_save_supplement.json'),JSON.stringify(res,null,2));
 const md=`# P23 Supplement — browser back after save\n\n- Request: \`${res.requestId}\`\n- Draft quote: \`${res.quoteId||'-'}\`\n- Result: ${res.quoteId?'TESTED':'BLOCKED'}\n\n## Network\n| Method/path | Status | Keys |\n|---|---:|---|\n${res.network.map(n=>`| ${n.method} ${n.path} | ${n.status} | ${(n.keys||[]).join(', ')} |`).join('\n')}\n\n## Evidence\n${res.snaps.map(s=>`- ${s.slug}: \`${s.png}\` — ${s.title} — ${s.url}`).join('\n')}\n\n## Notes\n${res.notes.map(n=>`- ${redact(n)}`).join('\n')||'- None.'}\n`;
 fs.writeFileSync(path.join(OUT,'p23_back_after_save_supplement.md'),md);
})();
