const { chromium } = require('playwright');
const fs=require('fs'), path=require('path');
const OUT=path.join(__dirname, '..', 'nestlancer-test-output', 'reports', 'P23'), EVID=path.join(OUT,'evidence_supplement'); fs.mkdirSync(EVID,{recursive:true});
const APP='https://app.nestlancer.com', ADMIN='https://admin.nestlancer.com', PASS='Brick2@Build', ARJUN='arjun.mehta@nestlancer.com', ADMIN_EMAIL='admin@nestlancer.com';
const RUN='AUDIT-P23-LINE-20261005-'+Date.now().toString(36).slice(-4);
function sanitizeUrl(u){try{const x=new URL(u); for(const k of [...x.searchParams.keys()]) if(/token|secret|signature|code|otp|password|cookie|auth|x-amz|t/i.test(k)) x.searchParams.set(k,'<redacted>'); return x.toString()}catch{return String(u||'')}}
function redact(s){return String(s??'').replaceAll(PASS,'<redacted-demo-password>').replace(/([A-Za-z0-9._%+-]+)@nestlancer\.com/g,'<demo-email>@nestlancer.com').replace(/eyJ[A-Za-z0-9._-]+/g,'<redacted-jwt>').slice(0,22000)}
async function snap(p,slug,res,extra={}){await p.waitForTimeout(600).catch(()=>{}); const png=path.join(EVID,slug+'.png'); await p.screenshot({path:png,fullPage:true}).catch(()=>{}); const text=redact(await p.locator('body').innerText({timeout:5000}).catch(e=>'ERR '+e.message)); const controls=await p.evaluate(()=>[...document.querySelectorAll('button,[role=button]')].map((b,i)=>({i,text:(b.textContent||b.getAttribute('aria-label')||'').trim(),disabled:b.disabled||b.getAttribute('aria-disabled')==='true',aria:b.getAttribute('aria-label'),title:b.getAttribute('title')})).slice(0,260)).catch(e=>[{error:e.message}]); fs.writeFileSync(path.join(EVID,slug+'.txt'),`URL: ${sanitizeUrl(p.url())}\nTITLE: ${await p.title().catch(()=> '')}\nEXTRA: ${JSON.stringify(extra)}\nCONTROLS: ${JSON.stringify(controls,null,2)}\n\n${text}`); res.snaps.push({slug,png:path.relative(OUT,png),url:sanitizeUrl(p.url()),title:await p.title().catch(()=>''),extra}); return {text,controls};}
async function loginClient(browser,res){const ctx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const p=await ctx.newPage(); await p.goto(APP+'/login',{waitUntil:'domcontentloaded'}); await p.locator('input[type=email]').fill(ARJUN); await p.locator('input[type=password]').fill(PASS); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:25000}),p.getByRole('button',{name:/sign in/i}).click()]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); return {ctx,p};}
async function loginAdmin(browser,res){const ctx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const p=await ctx.newPage(); p.on('response',async r=>{const req=r.request(); if(!/nestlancer\.com/.test(r.url()))return; if(!(/\/api\//.test(r.url())||req.resourceType()==='document'))return; let keys=[]; if(req.postData()){try{keys=Object.keys(JSON.parse(req.postData()))}catch{keys=['<non-json>']}} res.network.push({method:req.method(),path:(()=>{try{const u=new URL(sanitizeUrl(r.url())); return u.pathname+u.search}catch{return sanitizeUrl(r.url())}})(),status:r.status(),keys});}); await p.goto(ADMIN+'/login',{waitUntil:'domcontentloaded'}); await p.locator('input[type=email]').fill(ADMIN_EMAIL); await p.locator('input[type=password]').fill(PASS); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:25000}),p.getByRole('button',{name:/Enter console|sign in|log in/i}).click()]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); return {ctx,p};}
(async()=>{const res={requestId:null,network:[],snaps:[],verdicts:[]}; const browser=await chromium.launch({ headless: true}); const c=await loginClient(browser,res); const cp=c.p; await cp.goto(APP+'/requests/new',{waitUntil:'domcontentloaded'}); await cp.locator('#req-title').fill(RUN+' Request'); await cp.locator('#req-description').fill('P23 add/remove line supplement.'); await cp.locator('#req-budget-min').fill('1000'); await cp.locator('#req-budget-max').fill('2000'); await cp.locator('#req-requirements').fill('Add line/remove line evidence'); await Promise.allSettled([cp.waitForURL(u=>u.pathname!='/requests/new',{timeout:25000}),cp.getByRole('button',{name:/Save draft/i}).click()]); await cp.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); res.requestId=(new URL(cp.url()).pathname.match(/requests\/([^/]+)/)||[])[1]; await Promise.allSettled([cp.waitForResponse(r=>/\/api\/v1\/requests\/[^/]+\/submit$/.test(r.url()) && r.request().method()==='POST',{timeout:12000}), cp.getByRole('button',{name:/Submit for review/i}).click({timeout:8000})]); await cp.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await cp.waitForTimeout(1000); await c.ctx.close();
 const a=await loginAdmin(browser,res); const p=a.p; await p.goto(`${ADMIN}/requests/${res.requestId}/quote/new`,{waitUntil:'domcontentloaded'}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'supp_line_builder_initial',res); const fill=p.locator('input,textarea'); await fill.nth(1).fill('AUDIT-P23 add-remove phase'); await fill.nth(2).fill('AUDIT-P23 first line'); await fill.nth(3).fill('1'); await fill.nth(4).fill('1000'); await snap(p,'supp_line_before_add',res); let added=false, removed=false; try{await p.getByRole('button',{name:/Add line/i}).first().click({timeout:5000}); added=true;}catch(e){res.verdicts.push({control:'add-line',verdict:'NOT_CLICKED',error:e.message});} await snap(p,'supp_line_after_add',res,{added});
 // Try remove/delete controls if present; do not delete the priced first row if unsure.
 const buttons=await p.locator('button').evaluateAll(bs=>bs.map((b,i)=>({i,text:(b.textContent||'').trim(),aria:b.getAttribute('aria-label'),title:b.getAttribute('title'),disabled:b.disabled}))).catch(()=>[]); const del=buttons.find(b=>!b.disabled && /remove|delete|trash/i.test((b.text||'')+' '+(b.aria||'')+' '+(b.title||''))); if(del){try{await p.locator('button').nth(del.i).click({timeout:4000}); removed=true;}catch(e){res.verdicts.push({control:'remove-line',verdict:'CLICK_FAILED',error:e.message});}} else {res.verdicts.push({control:'remove-line',verdict:'NO_LABELLED_CONTROL_FOUND',note:'No remove/delete labelled button exposed after Add line; screenshot/control dump captured.'});} await snap(p,'supp_line_after_remove_attempt',res,{added,removed}); res.verdicts.push({control:'add-line',verdict:added?'PASS_CLICKED':'NOT_CLICKED'}); res.verdicts.push({control:'remove-line',verdict:removed?'PASS_CLICKED':'CONTROL_NOT_EXPOSED_OR_UNLABELLED'});
 await a.ctx.close(); await browser.close(); fs.writeFileSync(path.join(OUT,'p23_add_remove_line_supplement.json'),JSON.stringify(res,null,2)); const md=`# P23 Supplement — add/remove line controls\n\n- Request: \`${res.requestId}\`\n\n## Verdicts\n${res.verdicts.map(v=>`- ${v.control}: ${v.verdict}${v.error?` — ${redact(v.error)}`:''}${v.note?` — ${v.note}`:''}`).join('\n')}\n\n## Evidence\n${res.snaps.map(s=>`- ${s.slug}: \`${s.png}\` — ${s.title} — ${s.url}`).join('\n')}\n`; fs.writeFileSync(path.join(OUT,'p23_add_remove_line_supplement.md'),md);})();
