const { chromium } = require('playwright');
const fs=require('fs'), path=require('path');
const OUT='/home/bhumukul-raj/Music/nestlacer-test-output/reports/P24', EVID=path.join(OUT,'evidence');
const ADMIN='https://admin.nestlancer.com', PASS='Brick2@Build', ADMIN_EMAIL='admin@nestlancer.com';
function redact(s){return String(s??'').replaceAll(PASS,'<redacted-demo-password>').replace(/([A-Za-z0-9._%+-]+)@nestlancer\.com/g,'<demo-email>@nestlancer.com').replace(/eyJ[A-Za-z0-9._-]+/g,'<redacted-jwt>').slice(0,20000)}
async function snap(p,slug,res,extra={}){await p.waitForTimeout(700); const png=path.join(EVID,slug+'.png'); await p.screenshot({path:png,fullPage:true}).catch(()=>{}); const text=redact(await p.locator('body').innerText({timeout:5000}).catch(e=>e.message)); fs.writeFileSync(path.join(EVID,slug+'.txt'),`URL:${p.url()}\nTITLE:${await p.title().catch(()=> '')}\nEXTRA:${JSON.stringify(extra)}\n\n${text}`); res.snaps.push({slug,png:path.relative(OUT,png),url:p.url(),title:await p.title().catch(()=>''),extra});}
(async()=>{const prev=JSON.parse(fs.readFileSync(path.join(OUT,'p24_result.json'),'utf8')); const draftId=prev.fixtures?.draftQuote?.quoteId; const ID='01a106a1-cc7f-73ad-8f85-074e70e72c6f'; const res={snaps:[],apiRestore:null,notes:[]}; const b=await chromium.launch({ channel: 'chrome', headless: true}); const c=await b.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const p=await c.newPage(); await p.goto(ADMIN+'/login',{waitUntil:'domcontentloaded'}); await p.locator('input[type=email]').fill(ADMIN_EMAIL); await p.locator('input[type=password]').fill(PASS); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:25000}),p.getByRole('button',{name:/Enter console|sign in|log in/i}).click()]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{});
 res.apiRestore=await p.evaluate(async(ID)=>{const token=(await (await fetch('/api/auth/refresh',{method:'POST',credentials:'include'})).json()).data.accessToken; async function get(){return (await (await fetch('/api/v1/admin/quotes/line-item-library?includeInactive=true',{headers:{authorization:'Bearer '+token},credentials:'include'})).json()).data.blocks.find(x=>x.id===ID)} const before=await get(); if(before && !before.isActive){const body={label:before.label,description:before.description,category:before.category,defaultQuantity:before.defaultQuantity,defaultUnitPrice:before.defaultUnitPrice,isActive:true,sortOrder:before.sortOrder}; const r=await fetch('/api/v1/admin/quotes/line-item-library/'+ID,{method:'PATCH',headers:{authorization:'Bearer '+token,'content-type':'application/json'},credentials:'include',body:JSON.stringify(body)}); const after=await get(); return {usedApi:true,patchStatus:r.status,beforeActive:before.isActive,afterActive:after&&after.isActive,blockId:ID};} return {usedApi:false,beforeActive:before&&before.isActive,afterActive:before&&before.isActive,blockId:ID};},ID);
 await p.goto(`${ADMIN}/quotes/${draftId}`,{waitUntil:'domcontentloaded'}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await p.getByRole('button',{name:/Line-item library/i}).click({timeout:6000}).catch(e=>res.notes.push('open library '+e.message)); await p.waitForTimeout(1200); await snap(p,'admin_library_restore_verified_active',res,res.apiRestore);
 await c.close(); await b.close(); fs.writeFileSync(path.join(OUT,'p24_restore_library_api.json'),JSON.stringify(res,null,2)); const md=`# P24 corrective supplement — line-item library restored\n\n- Reason: P24 line-item-library probing clicked a seeded Deactivate control after the AUDIT create form remained disabled.\n- UI restore attempt: no Activate/Reactivate control was exposed for the inactive row.\n- API fallback used because the UI exposed no restore control: ${res.apiRestore.usedApi}\n- Patch status: ${res.apiRestore.patchStatus||'not needed'}\n- Discovery & Scoping before active: ${res.apiRestore.beforeActive}\n- Discovery & Scoping after active: ${res.apiRestore.afterActive}\n\n## Evidence\n${res.snaps.map(s=>`- ${s.slug}: \`${s.png}\` — ${s.title} — ${s.url}`).join('\n')}\n\n## Notes\n${res.notes.map(n=>`- ${redact(n)}`).join('\n')||'- None.'}\n`; fs.writeFileSync(path.join(OUT,'p24_restore_library_api.md'),md);})();
