const { chromium } = require('playwright');
const fs=require('fs'), path=require('path');
const OUT='/home/bhumukul-raj/Music/nestlacer-test-output/reports/P24', EVID=path.join(OUT,'evidence');
const ADMIN='https://admin.nestlancer.com', PASS='Brick2@Build', ADMIN_EMAIL='admin@nestlancer.com';
function redact(s){return String(s??'').replaceAll(PASS,'<redacted-demo-password>').replace(/([A-Za-z0-9._%+-]+)@nestlancer\.com/g,'<demo-email>@nestlancer.com').replace(/eyJ[A-Za-z0-9._-]+/g,'<redacted-jwt>').slice(0,20000)}
async function snap(p,slug,res,extra={}){await p.waitForTimeout(800); const png=path.join(EVID,slug+'.png'); await p.screenshot({path:png,fullPage:true}).catch(()=>{}); const text=redact(await p.locator('body').innerText({timeout:5000}).catch(e=>e.message)); fs.writeFileSync(path.join(EVID,slug+'.txt'),`URL:${p.url()}\nTITLE:${await p.title().catch(()=> '')}\nEXTRA:${JSON.stringify(extra)}\n\n${text}`); res.snaps.push({slug,png:path.relative(OUT,png),url:p.url(),title:await p.title().catch(()=>''),extra});}
(async()=>{const res={network:[],snaps:[],notes:[],reactivated:false}; const prev=JSON.parse(fs.readFileSync(path.join(OUT,'p24_result.json'),'utf8')); const draftId=prev.fixtures?.draftQuote?.quoteId; const b=await chromium.launch({ channel: 'chrome', headless: true}); const c=await b.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const p=await c.newPage(); p.on('response',async r=>{const req=r.request(); if(/nestlancer\.com/.test(r.url()) && (/\/api\//.test(r.url())||req.resourceType()==='document')){let keys=[]; if(req.postData()){try{keys=Object.keys(JSON.parse(req.postData()))}catch{keys=['<non-json>']}} res.network.push({method:req.method(),path:new URL(r.url()).pathname,status:r.status(),keys});}}); await p.goto(ADMIN+'/login',{waitUntil:'domcontentloaded'}); await p.locator('input[type=email]').fill(ADMIN_EMAIL); await p.locator('input[type=password]').fill(PASS); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:25000}),p.getByRole('button',{name:/Enter console|sign in|log in/i}).click()]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await p.goto(`${ADMIN}/quotes/${draftId}`,{waitUntil:'domcontentloaded'}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'admin_library_restore_detail',res,{draftId}); try{await p.getByRole('button',{name:/Line-item library/i}).click({timeout:5000}); await p.waitForTimeout(1000); await snap(p,'admin_library_restore_open',res); }catch(e){res.notes.push('open library failed '+e.message)}
 try{const show=p.getByRole('button',{name:/Show inactive/i}).first(); if(await show.count()){await show.click({timeout:5000}); await p.waitForTimeout(1000); await snap(p,'admin_library_restore_show_inactive',res);} }catch(e){res.notes.push('show inactive failed '+e.message)}
 try{const row=p.locator('text=Discovery & Scoping').first().locator('xpath=ancestor::*[self::tr or self::div][.//button][1]'); const activate=row.getByRole('button',{name:/Activate|Reactivate/i}).first(); if(await activate.count()){await activate.click({timeout:6000}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await p.waitForTimeout(1200); res.reactivated=true; await snap(p,'admin_library_restore_after_activate',res,{reactivated:true});} else {res.notes.push('No activate button found for Discovery & Scoping; it may already be active.'); await snap(p,'admin_library_restore_no_activate_needed',res);}}catch(e){res.notes.push('activate failed '+e.message); await snap(p,'admin_library_restore_activate_error',res,{error:e.message}).catch(()=>{});} await c.close(); await b.close(); fs.writeFileSync(path.join(OUT,'p24_restore_library.json'),JSON.stringify(res,null,2)); const md=`# P24 corrective supplement — line-item library restore\n\n- Purpose: restore any seeded library block accidentally deactivated during P24 line-item-library probing.\n- Reactivated Discovery & Scoping: ${res.reactivated}\n\n## Evidence\n${res.snaps.map(s=>`- ${s.slug}: \`${s.png}\` — ${s.title} — ${s.url}`).join('\n')}\n\n## Notes\n${res.notes.map(n=>`- ${redact(n)}`).join('\n')||'- None.'}\n`; fs.writeFileSync(path.join(OUT,'p24_restore_library.md'),md);})();
