const { chromium }=require('playwright');
const fs=require('fs'), path=require('path');
const OUT=path.join(__dirname, '..', 'nestlancer-test-output', 'reports', 'P25'), EVID=path.join(OUT,'evidence_supplement'); fs.mkdirSync(EVID,{recursive:true});
const ADMIN='https://admin.nestlancer.com', PASS='Brick2@Build', ADMIN_EMAIL='admin@nestlancer.com';
function redact(s){return String(s??'').replaceAll(PASS,'<redacted-demo-password>').replace(/([A-Za-z0-9._%+-]+)@nestlancer\.com/g,'<demo-email>@nestlancer.com').replace(/eyJ[A-Za-z0-9._-]+/g,'<redacted-jwt>').replace(/https:\/\/s3\.nestlancer\.com\/[^\s"'<>]+/gi,'https://s3.nestlancer.com/<signed-url-redacted>').slice(0,26000)}
async function snap(p,slug,res,extra={}){await p.waitForTimeout(700); const png=path.join(EVID,slug+'.png'); await p.screenshot({path:png,fullPage:true}).catch(()=>{}); const text=redact(await p.locator('body').innerText({timeout:5000}).catch(e=>e.message)); const controls=await p.evaluate(()=>[...document.querySelectorAll('button,[role=button],a[href],input,textarea,select')].map((el,i)=>({i,tag:el.tagName,text:(el.textContent||el.getAttribute('aria-label')||'').trim().slice(0,120),href:el.href,placeholder:el.getAttribute('placeholder'),value:(el.value||'').slice(0,80),disabled:el.disabled||el.getAttribute('aria-disabled')==='true',aria:el.getAttribute('aria-label')})).slice(0,260)).catch(()=>[]); fs.writeFileSync(path.join(EVID,slug+'.txt'),`URL:${p.url()}\nTITLE:${await p.title().catch(()=> '')}\nEXTRA:${redact(JSON.stringify(extra))}\nCONTROLS:${redact(JSON.stringify(controls,null,2))}\n\n${text}`); res.snaps.push({slug,png:path.relative(OUT,png),url:p.url(),title:await p.title().catch(()=>''),extra});}
async function closeDialog(p){for(const re of [/Cancel/i,/Close dialog/i,/Close/i]){try{const b=p.getByRole('button',{name:re}).last(); if(await b.isVisible({timeout:600})){await b.click({timeout:2000}); await p.waitForTimeout(500); return true;}}catch{}} try{await p.keyboard.press('Escape'); await p.waitForTimeout(500); return true;}catch{return false}}
(async()=>{const prev=JSON.parse(fs.readFileSync(path.join(OUT,'p25_result.json'),'utf8')); const projectId=prev.fixtures?.projectId; const res={projectId,network:[],snaps:[],controls:[],downloads:[],notes:[]}; const b=await chromium.launch({ headless: true}); const c=await b.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true,acceptDownloads:true}); const p=await c.newPage(); p.on('response',async r=>{const req=r.request(); if(/nestlancer\.com/.test(r.url())&&(/\/api\//.test(r.url())||req.resourceType()==='document')){let keys=[]; if(req.postData()){try{keys=Object.keys(JSON.parse(req.postData()))}catch{keys=['<non-json>']}} res.network.push({method:req.method(),path:new URL(r.url()).pathname,status:r.status(),keys});}}); await p.goto(ADMIN+'/login',{waitUntil:'domcontentloaded'}); await p.locator('input[type=email]').fill(ADMIN_EMAIL); await p.locator('input[type=password]').fill(PASS); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:25000}),p.getByRole('button',{name:/Enter console|sign in|log in/i}).click()]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await p.goto(`${ADMIN}/projects/${projectId}`,{waitUntil:'domcontentloaded'}); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(p,'supp_project_detail_initial',res);
 for(const [name,re] of [['overview',/Overview/i],['milestones_files',/Milestones & files|Milestones/i],['daily_progress',/Daily progress/i],['analytics',/Analytics/i]]){try{const el=p.getByRole('button',{name:re}).first(); if(await el.count()){await el.click({timeout:4000}); await p.waitForTimeout(800); await snap(p,`supp_tab_${name}`,res,{clicked:true}); res.controls.push({name,clicked:true});} else {const txt=p.getByText(re).first(); if(await txt.count()){await txt.click({timeout:4000}); await p.waitForTimeout(800); await snap(p,`supp_tab_${name}`,res,{clicked:true,via:'text'}); res.controls.push({name,clicked:true,via:'text'});} else res.controls.push({name,clicked:false,note:'not found'});} }catch(e){res.controls.push({name,clicked:false,error:e.message}); await snap(p,`supp_tab_${name}_error`,res,{error:e.message}).catch(()=>{});} }
 // Export: click and capture whether download/network/toast appears.
 try{await p.goto(`${ADMIN}/projects/${projectId}`,{waitUntil:'domcontentloaded'}); await p.waitForLoadState('networkidle',{timeout:8000}).catch(()=>{}); const dlP=p.waitForEvent('download',{timeout:7000}).catch(e=>({error:e.message})); await p.getByRole('button',{name:/Export/i}).click({timeout:5000}); const dl=await dlP; if(dl&&!dl.error){const fn=dl.suggestedFilename(); const save=path.join(EVID,'supp_export_'+fn.replace(/[^a-zA-Z0-9._-]+/g,'_')); await dl.saveAs(save); res.downloads.push({slug:'supp_export',verdict:'DOWNLOADED',filename:fn,bytes:fs.statSync(save).size,relative:path.relative(OUT,save)});} else res.downloads.push({slug:'supp_export',verdict:'NO_DOWNLOAD_EVENT',error:dl.error}); await snap(p,'supp_export_after_click',res,{download:res.downloads.at(-1)});}catch(e){res.downloads.push({slug:'supp_export',verdict:'ERROR',error:e.message}); await snap(p,'supp_export_error',res,{error:e.message}).catch(()=>{});}
 await closeDialog(p);
 // Status dialog: open and cancel, do not mutate because project is pending payment.
 try{await p.getByRole('button',{name:/Update status/i}).click({timeout:5000}); await p.waitForTimeout(900); await snap(p,'supp_status_dialog_opened',res,{mutated:false,reason:'project is pending payment; no status committed'}); await closeDialog(p); res.controls.push({name:'status-dialog',clicked:true,mutated:false});}catch(e){res.controls.push({name:'status-dialog',clicked:false,error:e.message}); await snap(p,'supp_status_dialog_error',res,{error:e.message}).catch(()=>{});}
 // Archive dialog: open/cancel only.
 try{await p.getByRole('button',{name:/^Archive$/i}).click({timeout:5000}); await p.waitForTimeout(900); await snap(p,'supp_archive_dialog_opened',res,{mutated:false}); await closeDialog(p); res.controls.push({name:'archive-dialog',clicked:true,mutated:false});}catch(e){res.controls.push({name:'archive-dialog',clicked:false,error:e.message}); await snap(p,'supp_archive_dialog_error',res,{error:e.message}).catch(()=>{});}
 // Template/duplicate wizard: open, next validation, cancel.
 try{await p.getByRole('button',{name:/Use as template/i}).click({timeout:5000}); await p.waitForTimeout(800); await snap(p,'supp_template_wizard_step1',res); await p.getByRole('button',{name:/Next/i}).click({timeout:4000}).catch(e=>res.notes.push('template next step1 '+e.message)); await p.waitForTimeout(800); await snap(p,'supp_template_wizard_after_next',res); await closeDialog(p); res.controls.push({name:'use-as-template-wizard',clicked:true,executed:false});}catch(e){res.controls.push({name:'use-as-template-wizard',clicked:false,error:e.message}); await snap(p,'supp_template_wizard_error',res,{error:e.message}).catch(()=>{});}
 // Change operator dialog and remove button inventory only.
 try{await p.getByRole('button',{name:/Change operator/i}).click({timeout:5000}); await p.waitForTimeout(800); await snap(p,'supp_change_operator_dialog',res,{mutated:false}); await closeDialog(p); res.controls.push({name:'change-operator-dialog',clicked:true,mutated:false});}catch(e){res.controls.push({name:'change-operator-dialog',clicked:false,error:e.message}); await snap(p,'supp_change_operator_error',res,{error:e.message}).catch(()=>{});}
 await c.close(); await b.close(); fs.writeFileSync(path.join(OUT,'p25_controls_supplement.json'),JSON.stringify(res,null,2)); const md=`# P25 Supplement — project controls/dialogs\n\n- Project: \`${projectId}\`\n- Purpose: close modal-interception gap from first run and explicitly inventory status/archive/export/template/operator controls.\n\n## Controls\n${res.controls.map(c=>`- ${c.name}: clicked=${!!c.clicked}; mutated=${c.mutated===undefined?'-':c.mutated}; ${c.error?'error='+redact(c.error):c.note||''}`).join('\n')}\n\n## Downloads\n${res.downloads.map(d=>`- ${d.slug}: ${d.verdict}; file=${d.filename||'-'}; bytes=${d.bytes||'-'}; error=${d.error?redact(d.error):'-'}`).join('\n')||'- None.'}\n\n## Network\n| Method/path | Status | Keys |\n|---|---:|---|\n${res.network.filter(n=>/projects|export|templates|status|archive|operator/i.test(n.path)).map(n=>`| ${n.method} ${n.path} | ${n.status} | ${(n.keys||[]).join(', ')} |`).join('\n')||'| - | - | - |'}\n\n## Evidence\n${res.snaps.map(s=>`- ${s.slug}: \`${s.png}\` — ${s.title} — ${s.url}`).join('\n')}\n\n## Notes\n${res.notes.map(n=>`- ${redact(n)}`).join('\n')||'- None.'}\n`; fs.writeFileSync(path.join(OUT,'p25_controls_supplement.md'),md);})();
