const { chromium } = require('playwright');
const fs=require('fs'); const path=require('path'); const { execFileSync }=require('child_process');
const { analyzePdfs: analyzePdfsHelper, integrityBugsFromAnalysis, markdownIntegrityTable } = require('./lib/pdf_analyze');
const OUT='/home/bhumukul-raj/Music/nestlacer-test-output/reports/P25'; const EVID=path.join(OUT,'evidence'); fs.mkdirSync(EVID,{recursive:true});
const APP='https://app.nestlancer.com', ADMIN='https://admin.nestlancer.com';
const PASS='Brick2@Build', ARJUN='arjun.mehta@nestlancer.com', RAHUL='rahul.desai@nestlancer.com', ADMIN_EMAIL='admin@nestlancer.com';
const RUN='AUDIT-P25-20261005-'+Date.now().toString(36).slice(-5);
function shortEmail(e){const [l,d]=String(e).split('@');return `${l.slice(0,10)}…@${d}`}
function sanitizeUrl(u){try{const x=new URL(u); for(const k of [...x.searchParams.keys()]) if(/token|code|otp|secret|password|signature|cookie|auth|x-amz|t/i.test(k)) x.searchParams.set(k,'<redacted>'); if(x.hostname==='s3.nestlancer.com') return 'https://s3.nestlancer.com/<signed-document-url-redacted>'; return x.toString();}catch{return String(u||'')}}
function redact(s){return String(s??'').replaceAll(PASS,'<redacted-demo-password>').replace(/([A-Za-z0-9._%+-]+)@nestlancer\.com/g,'<demo-email>@nestlancer.com').replace(/https:\/\/s3\.nestlancer\.com\/[^\s"'<>]+/gi,'https://s3.nestlancer.com/<signed-url-redacted>').replace(/eyJ[A-Za-z0-9._-]+/g,'<redacted-jwt>').replace(/(token|otp|code|secret|password|signature|cookie|authorization|credential)(["'\s:=]+)([^\s"'<>]+)/gi,'$1$2<redacted>').slice(0,32000)}
async function dismiss(p){for(const n of ['Accept','Dismiss']){try{const b=p.getByRole('button',{name:n}).first(); if(await b.isVisible({timeout:600})) await b.click({timeout:1200});}catch{}}}
async function attach(p,res,label){const started=new Map(); p.on('request',r=>started.set(r,Date.now())); p.on('response',async r=>{const req=r.request(); let u=sanitizeUrl(r.url()); if(!/nestlancer\.com/.test(u))return; if(!(req.resourceType()==='document'||/\/api\//.test(u)||/project|quote|request|export|duplicate|archive|team|status|document|agreement|pdf/i.test(u)))return; let keys=[]; if(req.postData()){try{keys=Object.keys(JSON.parse(req.postData()))}catch{keys=['<non-json-post-body>']}} const h=r.headers(); res.network.push({label,method:req.method(),status:r.status(),path:(()=>{try{const uu=new URL(u);return uu.pathname+uu.search}catch{return u}})(),type:req.resourceType(),keys,contentType:(h['content-type']||'').split(';')[0],contentDisposition:redact(h['content-disposition']||''),ms:started.has(req)?Date.now()-started.get(req):null}); try{const raw=new URL(r.url()).pathname; if(req.method()==='POST'&&/\/api\/v1\/admin\/requests\/[^/]+\/quotes$/.test(raw)){const j=await r.json(); if(j?.data?.id)res.lastQuoteId=j.data.id;} }catch{}}); p.on('console',m=>{if(['error','warning'].includes(m.type()))res.console.push({label,type:m.type(),text:redact(m.text())})}); p.on('pageerror',e=>res.console.push({label,type:'pageerror',text:redact(e.message||String(e))}));}
async function snap(p,slug,res,extra={}){await p.waitForTimeout(700).catch(()=>{}); const png=path.join(EVID,slug+'.png'); await p.screenshot({path:png,fullPage:true}).catch(e=>res.notes.push('screenshot '+slug+': '+e.message)); const title=await p.title().catch(()=>''), url=sanitizeUrl(p.url()); const text=redact(await p.locator('body').innerText({timeout:7000}).catch(e=>'ERR '+e.message)); const controls=await p.evaluate(()=>({buttons:[...document.querySelectorAll('button,[role=button]')].map((b,i)=>({i,text:(b.textContent||b.getAttribute('aria-label')||'').trim().slice(0,160),disabled:b.disabled||b.getAttribute('aria-disabled')==='true',aria:b.getAttribute('aria-label'),title:b.getAttribute('title')})).slice(0,260),links:[...document.querySelectorAll('a[href]')].map((a,i)=>({i,text:(a.textContent||'').trim().slice(0,160),href:a.href,row:(a.closest('tr')?.innerText||'').trim().slice(0,300)})).slice(0,260),inputs:[...document.querySelectorAll('input,textarea,select')].map((el,i)=>({i,tag:el.tagName,type:el.getAttribute('type')||el.type,name:el.getAttribute('name'),id:el.id,placeholder:el.getAttribute('placeholder'),value:(el.value||'').slice(0,80),checked:el.checked})).slice(0,220)})).catch(e=>({error:e.message})); controls.links=(controls.links||[]).map(l=>({...l,href:sanitizeUrl(l.href)})); fs.writeFileSync(path.join(EVID,slug+'.txt'),`URL: ${url}\nTITLE: ${title}\nEXTRA: ${redact(JSON.stringify(extra))}\nCONTROLS: ${redact(JSON.stringify(controls,null,2))}\n\n${text}`); res.snapshots.push({slug,file:png,url,title,extra}); return {url,title,text,controls};}
async function goto(p,url,slug,res){const rec={slug,requestedUrl:sanitizeUrl(url)}; try{const r=await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000}); rec.status=r?r.status():null; await p.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); const s=await snap(p,slug,res,{httpStatus:rec.status}); rec.finalUrl=s.url; rec.title=s.title; rec.ok=!!r&&rec.status<500;}catch(e){rec.error=e.message; await snap(p,slug+'_error',res,{error:e.message}).catch(()=>{});} res.steps.push(rec); return rec;}
async function clientLogin(browser,email,label,res){const ctx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true,acceptDownloads:true}); const p=await ctx.newPage(); await attach(p,res,label); await p.goto(APP+'/login',{waitUntil:'domcontentloaded'}); await dismiss(p); await p.locator('input[type=email]').fill(email); await p.locator('input[type=password]').fill(PASS); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:25000}),p.getByRole('button',{name:/sign in/i}).click({timeout:6000})]); await p.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); await snap(p,label+'_login_after',res,{account:shortEmail(email)}); return {ctx,page:p};}
async function adminLogin(browser,res,viewport={width:1365,height:900}){const ctx=await browser.newContext({viewport,ignoreHTTPSErrors:true,acceptDownloads:true}); const p=await ctx.newPage(); await attach(p,res,'admin'); await p.goto(ADMIN+'/login',{waitUntil:'domcontentloaded'}); await dismiss(p); await p.locator('input[type=email]').fill(ADMIN_EMAIL); await p.locator('input[type=password]').fill(PASS); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:25000}),p.getByRole('button',{name:/Enter console|sign in|log in/i}).click({timeout:6000})]); await p.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); await snap(p,`admin_login_after_${viewport.width}`,res,{viewport}); return {ctx,page:p};}
async function createRequest(browser,res){const c=await clientLogin(browser,ARJUN,'client_setup',res); const p=c.page; const title=`${RUN} Project Fixture`; await goto(p,APP+'/requests/new','client_setup_request_new',res); await p.locator('#req-title').fill(title); await p.locator('#req-description').fill('P25 audit project fixture for admin project list/detail/status/team/export/duplicate coverage.'); await p.locator('#req-budget-min').fill('1000'); await p.locator('#req-budget-max').fill('3000'); await p.locator('#req-requirements').fill('AUDIT-P25 project setup\nAdmin project management coverage\nDo not use production data'); await snap(p,'client_setup_request_filled',res); await Promise.allSettled([p.waitForURL(u=>u.pathname!='/requests/new',{timeout:25000}),p.getByRole('button',{name:/Save draft/i}).click({timeout:6000})]); await p.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); const reqId=(new URL(p.url()).pathname.match(/requests\/([^/]+)/)||[])[1]; await snap(p,'client_setup_request_draft',res,{reqId}); await Promise.allSettled([p.waitForResponse(r=>/\/api\/v1\/requests\/[^/]+\/submit$/.test(r.url())&&r.request().method()==='POST',{timeout:15000}),p.getByRole('button',{name:/Submit for review/i}).click({timeout:8000})]); await p.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); await snap(p,'client_setup_request_submitted',res,{reqId}); await c.ctx.close().catch(()=>{}); return {reqId,title};}
async function createAndSendQuote(browser,res,req){const a=await adminLogin(browser,res); const p=a.page; res.lastQuoteId=null; await goto(p,`${ADMIN}/requests/${req.reqId}/quote/new`,'admin_setup_quote_builder',res); const f=p.locator('input,textarea'); await f.nth(1).fill('AUDIT-P25 Project phase'); await f.nth(2).fill('AUDIT-P25 project fixture deliverable safe text <img src=x onerror=alert(1)>'); await f.nth(3).fill('1'); await f.nth(4).fill('1250'); await snap(p,'admin_setup_quote_line_item',res); await p.getByRole('button',{name:/Next/i}).click({timeout:6000}); await p.waitForTimeout(800); await snap(p,'admin_setup_quote_pricing',res); await p.getByRole('button',{name:/Next/i}).click({timeout:6000}); await p.waitForTimeout(800); await snap(p,'admin_setup_quote_terms',res); await p.getByRole('button',{name:/Create quote/i}).click({timeout:8000}); await p.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); await p.waitForTimeout(1600); await snap(p,'admin_setup_quote_created',res); const q=res.lastQuoteId; if(q){await goto(p,`${ADMIN}/requests/${req.reqId}/quote/edit`,'admin_setup_quote_edit_before_send',res); await p.getByRole('button',{name:/^Send$|Send to client/i}).first().click({timeout:8000}); await p.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); await p.waitForTimeout(1600); await snap(p,'admin_setup_quote_sent',res);} await a.ctx.close().catch(()=>{}); return q;}
async function acceptQuote(browser,res,quoteId,title){const c=await clientLogin(browser,ARJUN,'client_accept',res); const p=c.page; await goto(p,`${APP}/quotes/${quoteId}`,'client_setup_quote_detail_before_accept',res); try{await p.getByLabel(/I have read|agree to the terms/i).check({timeout:5000});}catch{try{await p.locator('input[type=checkbox]').first().check({timeout:5000});}catch(e){res.notes.push('accept checkbox '+e.message)}} try{await p.getByLabel(/Legal name/i).fill('Arjun Mehta');}catch{try{await p.locator('input').last().fill('Arjun Mehta');}catch(e){res.notes.push('legal name '+e.message)}} await snap(p,'client_setup_quote_accept_ready',res); await p.getByRole('button',{name:/Accept quote|sign agreement|Accept.*sign/i}).first().click({timeout:10000}).catch(e=>res.notes.push('accept click '+e.message)); await p.waitForLoadState('networkidle',{timeout:20000}).catch(()=>{}); await p.waitForTimeout(2500); await snap(p,'client_setup_quote_after_accept',res); // Find project id in current page or project list.
 let projectId=(new URL(p.url()).pathname.match(/projects\/([^/]+)/)||[])[1]; if(!projectId){await goto(p,APP+'/projects','client_projects_after_accept',res); const links=await p.evaluate((title)=>[...document.querySelectorAll('a[href*="/projects/"]')].map(a=>({href:a.href,text:a.textContent||'',row:a.closest('tr')?.innerText||''})).filter(x=>(x.text+x.row).includes(title)||/AUDIT-P25/.test(x.text+x.row)),title).catch(()=>[]); if(links[0]) projectId=(new URL(links[0].href)).pathname.split('/projects/')[1]; await snap(p,'client_projects_after_accept_scanned',res,{projectId}); }
 await c.ctx.close().catch(()=>{}); return projectId;}
async function downloadButton(p,re,slug,res){const rec={slug,control:String(re),verdict:'NOT_CLICKED'}; try{const b=p.getByRole('button',{name:re}).first(); if(!(await b.count())){rec.verdict='MISSING'; res.downloads.push(rec); return rec;} const dlP=p.waitForEvent('download',{timeout:22000}).catch(e=>({error:e.message})); await b.click({timeout:7000}); const dl=await dlP; if(dl&&!dl.error){const fn=dl.suggestedFilename(); const save=path.join(EVID,slug+'_'+fn.replace(/[^a-zA-Z0-9._-]+/g,'_')); await dl.saveAs(save); rec.verdict='DOWNLOADED'; rec.filename=fn; rec.savedAs=save; rec.bytes=fs.statSync(save).size; rec.relative=path.relative(OUT,save); rec.tokenLeakInFilename=/token|secret|signature|credential|jwt|access/i.test(fn);} else {rec.verdict='NO_DOWNLOAD_EVENT'; rec.error=dl?.error||'';} }catch(e){rec.verdict='ERROR'; rec.error=e.message;} res.downloads.push(rec); return rec;}
async function clickControl(p,re,slug,res,mode='click'){const rec={slug,control:String(re),clicked:false}; try{const b=p.getByRole('button',{name:re}).first(); if(await b.count()){await b.click({timeout:8000}); rec.clicked=true; await p.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); await p.waitForTimeout(1000); await snap(p,slug,res,{control:String(re),mode});} else await snap(p,slug+'_missing',res,{missing:String(re)});}catch(e){rec.error=e.message; await snap(p,slug+'_error',res,{error:e.message}).catch(()=>{});} res.controls.push(rec); return rec;}
function analyzePdfs(paths){return analyzePdfsHelper(paths,{extractVerifyUrls:false}).analysis;}
(async()=>{const res={prompt:'P25',runId:RUN,generatedAt:new Date().toISOString(),steps:[],snapshots:[],network:[],console:[],downloads:[],pdfIntegrity:[],controls:[],bugs:[],blockers:[],securityFindings:[],notes:[],lastQuoteId:null}; const browser=await chromium.launch({ channel: 'chrome', headless: true});
 const req=await createRequest(browser,res); const quoteId=await createAndSendQuote(browser,res,req); const projectId=quoteId?await acceptQuote(browser,res,quoteId,req.title):null; res.fixtures={reqId:req.reqId,quoteId,projectId,title:req.title}; if(!projectId) res.blockers.push('AUDIT-P25 project ID was not found after quote acceptance; project-detail mutation checks could not execute.');
 const admin=await adminLogin(browser,res); const p=admin.page; res.storage=await p.evaluate(()=>({localStorageKeys:Object.keys(localStorage),sessionStorageKeys:Object.keys(sessionStorage)})).catch(e=>({error:e.message})); res.storage.cookies=(await admin.ctx.cookies()).map(c=>({name:c.name,domain:c.domain,path:c.path,expires:c.expires,secure:c.secure,httpOnly:c.httpOnly,sameSite:c.sameSite}));
 for(const [url,slug] of [[`${ADMIN}/projects`,'admin_projects_list'],[`${ADMIN}/projects/archive`,'admin_projects_archive'],[`${ADMIN}/projects/completed`,'admin_projects_completed'],[`${ADMIN}/projects/stats`,'admin_projects_stats'],[`${ADMIN}/projects/new`,'admin_projects_new_redirect'],[`${ADMIN}/projects/not-a-real-id`,'admin_projects_invalid_id']]) await goto(p,url,slug,res);
 if(projectId){await goto(p,`${ADMIN}/projects/${projectId}`,'admin_project_detail_overview',res); for(const re of [/Overview/i,/Team/i,/Milestones/i,/Payments/i,/Files/i,/Activity|History/i]) await clickControl(p,re,`admin_project_tab_${String(re).replace(/\W+/g,'_').slice(1,30)}`,res,'tab'); await downloadButton(p,/Export|Download export|Export project/i,'admin_project_export',res); await clickControl(p,/Duplicate project|Duplicate/i,'admin_project_duplicate_wizard',res); await clickControl(p,/Cancel|Close/i,'admin_project_duplicate_cancel',res); await clickControl(p,/Use as template/i,'admin_project_use_as_template_inventory',res); await clickControl(p,/Archive project|Archive/i,'admin_project_archive_probe',res); // if archived, attempt unarchive
 await clickControl(p,/Unarchive|Restore project/i,'admin_project_unarchive_probe',res); await clickControl(p,/Change status|Update status|Status/i,'admin_project_status_control_probe',res); await snap(p,'admin_project_detail_after_controls',res);}
 const client=await clientLogin(browser,ARJUN,'client_verify',res); if(projectId) await goto(client.page,`${APP}/projects/${projectId}`,'client_project_detail_after_admin',res); await client.ctx.close().catch(()=>{});
 const rahul=await clientLogin(browser,RAHUL,'security_rahul',res); if(projectId) await goto(rahul.page,`${APP}/projects/${projectId}`,'security_rahul_attempt_p25_project',res); const rt=fs.existsSync(path.join(EVID,'security_rahul_attempt_p25_project.txt'))?fs.readFileSync(path.join(EVID,'security_rahul_attempt_p25_project.txt'),'utf8'):''; const idor=rt.includes(RUN)||rt.includes('AUDIT-P25'); if(idor) res.bugs.push({id:'NL-BUG-P25-IDOR-1',severity:'P0',title:'Other client can view AUDIT-P25 project',evidence:'security_rahul_attempt_p25_project'}); res.securityFindings.push({id:'P25-CLIENT-IDOR',severity:idor?'P0':'PASS',surface:'client project detail',role:'other client',impact:idor?'Other client saw AUDIT-P25 project':'Other client denied/no audit content',evidence:'security_rahul_attempt_p25_project',fix:idor?'Enforce project ownership checks':'No fix'}); await rahul.ctx.close().catch(()=>{});
 const anon=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const ap=await anon.newPage(); await attach(ap,res,'anon'); if(projectId) await goto(ap,`${ADMIN}/projects/${projectId}`,'security_anon_admin_project_guard',res); await anon.close().catch(()=>{});
 const mob=await adminLogin(browser,res,{width:375,height:812}); await goto(mob.page,`${ADMIN}/projects`,'mobile_admin_projects_375',res); if(projectId) await goto(mob.page,`${ADMIN}/projects/${projectId}`,'mobile_admin_project_detail_375',res); await mob.ctx.close().catch(()=>{});
 await goto(p,`${ADMIN}/projects`,'keyboard_projects_start',res); for(let i=0;i<24;i++) await p.keyboard.press('Tab').catch(()=>{}); await snap(p,'keyboard_projects_after_tabs',res);
 await admin.ctx.close().catch(()=>{}); await browser.close();
 try{const pdfs=res.downloads.filter(d=>d.savedAs&&/\.pdf$/i.test(d.savedAs)).map(d=>d.savedAs); res.pdfIntegrity=analyzePdfs(pdfs); if(res.pdfIntegrity.length) fs.writeFileSync(path.join(EVID,'pdf_integrity_analysis.json'),JSON.stringify(res.pdfIntegrity,null,2));}catch(e){res.notes.push('pdf integrity '+e.message)}
 for (const b of integrityBugsFromAnalysis(res.pdfIntegrity||[],{bugId:'NL-BUG-P25-DOCS-1',titlePrefix:'P25 export/document PDF'})) res.bugs.push(b);
 const anchors=['ProjectsClient.tsx','AdminProjectDetailClient.tsx','AdminProjectOverviewPanel.tsx','AdminDuplicateProjectWizard.tsx','AdminProjectSummaryStrip.tsx','admin-project-detail-tabs.ts']; res.sourceAnchorAudit=anchors.map(a=>({anchor:a,found:false,note:'Source files not present in prompt repo clone; runtime UI/network evidence used.'}));
 fs.writeFileSync(path.join(OUT,'p25_result.json'),JSON.stringify(res,null,2));
 const highest=res.bugs.find(b=>b.severity==='P0')?'P0':res.bugs.find(b=>b.severity==='P1')?'P1':res.bugs.find(b=>b.severity==='P2')?'P2':(res.blockers.length?'BLOCKED':'INFO');
 const cov=[['Audit project setup','client request → admin quote → client accept','TESTED_MUTATED_AUDIT','client_setup*/admin_setup*/client_setup_quote_*',`Project ${projectId||'-'}`],['Project list/routes','/projects/archive/completed/stats/new/invalid','TESTED','admin_projects_*','Lists, KPI routes, redirects and invalid ID'],['Project detail overview','/projects/[id]','TESTED', 'admin_project_detail_overview','Metadata/client/status/history summary captured'],['Tabs/panels','overview/team/milestones/payments/files/history','TESTED_OR_NOT_EXPOSED','admin_project_tab_*','Buttons clicked where exposed; missing controls recorded'],['Status/team/archive','status/team/archive/unarchive controls','TESTED_OR_BLOCKED','admin_project_*_probe','Mutated only if explicit AUDIT control exposed'],['Export','project export/download','TESTED_OR_BLOCKED','admin_project_export','Download result in table'],['Duplicate/template','duplicate wizard/use as template','TESTED_OR_CANCELLED','admin_project_duplicate_*','Wizard opened/cancelled if exposed; no non-AUDIT project duplicated'],['Client reflection','client project detail','TESTED','client_project_detail_after_admin','Client update visibility checked'],['Security','anonymous/wrong client','TESTED','security_*','Admin login guard and owner checks'],['Mobile/keyboard','375px + tab traversal','TESTED','mobile_* / keyboard_projects_after_tabs','Responsive/table/accessibility evidence']].map(r=>`| ${r[0]} | ${r[1]} | ${r[2]} | ${r[3]} | ${r[4]} |`).join('\n');
 const controls=res.controls.map(c=>`| ${c.slug} | ${c.control} | ${c.clicked?'CLICKED':'NOT_FOUND_OR_NOT_CLICKED'} | ${c.error?redact(c.error):'OK'} |`).join('\n')||'| - | - | - | - |';
 const downloads=res.downloads.map(d=>`| ${d.slug} | ${d.verdict} | ${d.filename||'-'} | ${d.bytes||'-'} | ${d.tokenLeakInFilename===false?'No':d.tokenLeakInFilename===true?'YES':'-'} | ${d.relative||'-'} | ${d.error?redact(d.error):''} |`).join('\n')||'| - | - | - | - | - | - | - |';
 const pdfRows=(res.pdfIntegrity||[]).length?markdownIntegrityTable(res.pdfIntegrity, redact):'| Not applicable | - | - | - | N/A | - | No generated PDF downloaded. |';
 const net=res.network.slice(0,280).map(n=>`| ${n.label} | ${n.method} ${n.path} | ${n.status} | ${n.status<400?'OK':'CHECK'} | keys: ${(n.keys||[]).join(', ')}; ${n.contentType||''}; ${n.ms??''}ms |`).join('\n');
 const bugs=res.bugs.length?res.bugs.map(b=>`### ${b.id}: ${b.title}\n- Severity: ${b.severity}\n- Evidence: ${b.evidence}\n${b.details?'- Details:\n'+(Array.isArray(b.details)?b.details.map(x=>`  - ${redact(x)}`).join('\n'):redact(JSON.stringify(b.details))):''}`).join('\n\n'):'No confirmed P25 app bugs.';
 const blockers=res.blockers.map(b=>`- ${redact(b)}`).join('\n')||'- None.';
 const sec=res.securityFindings.map(f=>`| ${f.id} | ${f.severity} | ${f.surface} | ${f.role} | ${f.impact} | ${f.evidence} | ${f.fix} |`).join('\n')||'| - | - | - | - | - | - | - |';
 const consoleRows=res.console.slice(0,100).map(c=>`| ${c.label} | ${c.type} | ${redact(c.text).replace(/\n/g,' ')} |`).join('\n')||'| - | - | No console warnings/errors captured. |';
 const source=res.sourceAnchorAudit.map(x=>`| ${x.anchor} | ${x.found?'Yes':'No'} | ${x.note} |`).join('\n');
 const storageRows=[`| localStorage keys | ${(res.storage?.localStorageKeys||[]).join(', ')||'-'} | Values not captured |`,`| sessionStorage keys | ${(res.storage?.sessionStorageKeys||[]).join(', ')||'-'} | Values not captured |`].concat((res.storage?.cookies||[]).map(c=>`| cookie ${c.name} | domain=${c.domain}; path=${c.path}; secure=${c.secure}; httpOnly=${c.httpOnly}; sameSite=${c.sameSite}; expires=${c.expires} | Value not captured |`)).join('\n');
 const shots=res.snapshots.map(s=>`- ${s.slug}: \`evidence/${path.basename(s.file)}\` — ${s.title} — ${s.url}`).join('\n');
 const md=`# Result — P25 — Admin projects list/detail overview, team, status, export and duplicate\n\n## Session summary\n- Host/environment: public-domain admin \`${ADMIN}\` and client portal \`${APP}\`.\n- Browser/MCP/tooling: Playwright Chromium headless, UI-first; generated-file/PDF integrity helper where files downloaded.\n- Role/account used: admin/operator plus ${shortEmail(ARJUN)} and wrong-client ${shortEmail(RAHUL)}.\n- Fixtures created: request \`${req.reqId}\`, quote \`${quoteId||'-'}\`, project \`${projectId||'-'}\`.\n- Routes walked: /projects, /projects/archive, /projects/completed, /projects/stats, /projects/new redirect, /projects/[id], invalid ID, client comparison, anonymous/wrong-client guards, mobile/keyboard.\n- Highest severity: ${highest}\n\n## Coverage table\n| Unit | Route/subsurface | Status | Evidence | Notes |\n|---|---|---|---|---|\n${cov}\n\n## Control inventory deltas\n| Evidence slug | Control/tab/dialog | Runtime verdict | Notes |\n|---|---|---|---|\n${controls}\n\n## Source anchor audit\n| Anchor | Found in prompt repo? | Note |\n|---|---|---|\n${source}\n\n## Download observations\n| Trigger | Verdict | Filename | Bytes | Token leak in filename | Saved evidence | Error |\n|---|---|---|---:|---|---|---|\n${downloads}\n\n## PDF/generated-document professional-integrity analysis\n| File | Pages | Bytes | Integrity verdict | Issues / warnings |\n|---|---:|---:|---|---|\n${pdfRows}\n\n## Storage/cookie metadata\n| Type | Keys / attributes | Value policy |\n|---|---|---|\n${storageRows}\n\n## Network/API observations\n| Trigger | Method + path | Status | Verdict | Notes |\n|---|---|---:|---|---|\n${net}\n\n## Console findings\n| Context | Type | Message |\n|---|---|---|\n${consoleRows}\n\n## Blockers / deferred checks\n${blockers}\n\n## Bugs\n${bugs}\n\n## Security findings\n| ID | Severity | Surface | Role | Impact | Evidence | Fix/regression |\n|---|---|---|---|---|---|---|\n${sec}\n\n## Handoff\n- Backend/API: verify project export/duplicate/archive operations expose clear audit/history entries and safe download URLs.\n- Frontend/UI: keep destructive/archive/duplicate paths gated with confirmation and visible status feedback.\n- Data/setup: AUDIT-P25 project was created for project-management coverage; avoid completing or billing it unless a later prompt explicitly requires lifecycle continuation.\n\n## Evidence files\n${shots}\n`;
 fs.writeFileSync(path.join(OUT,'result.md'),md);
})();
