const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
const OUT='/home/bhumukul-raj/Music/nestlacer-test-output/reports/P18'; const EVID=path.join(OUT,'evidence'); fs.mkdirSync(EVID,{recursive:true});
const ADMIN='https://admin.nestlancer.com'; const APP='https://app.nestlancer.com'; const ADMIN_EMAIL='admin@nestlancer.com'; const CLIENT_EMAIL='arjun.mehta@nestlancer.com'; const PASS='Brick2@Build';
function sanitizeUrl(u){try{const url=new URL(u); for(const k of [...url.searchParams.keys()]) if(/token|code|otp|password|secret|signature|key|auth|session|cookie|credential|expires|signed|x-amz|t/i.test(k)) url.searchParams.set(k,'<redacted>'); return url.toString();}catch{return String(u||'')}}
function redact(s){return String(s??'').replaceAll(PASS,'<redacted-demo-password>').replace(/([A-Za-z0-9._%+-]+)@nestlancer\.com/g,'<demo-email>@nestlancer.com').replace(/(token|otp|code|secret|password|signature|cookie|authorization|credential|turnstile)(["'\s:=]+)([^\s"'<>]+)/gi,'$1$2<redacted>').replace(/eyJ[A-Za-z0-9._-]+/g,'<redacted-jwt>').replace(/\b\d{6}\b/g,'<redacted-6digit-code>').slice(0,22000)}
async function dismiss(page){for(const t of ['Accept','Dismiss']){try{const b=page.getByRole('button',{name:t}).first(); if(await b.isVisible({timeout:700})) await b.click({timeout:1200});}catch{}}}
async function attach(page,label,result){const started=new Map(); page.on('request',req=>started.set(req,Date.now())); page.on('response',async res=>{const req=res.request(); const u=sanitizeUrl(res.url()); if(!/nestlancer\.com/.test(u)) return; const interesting=req.resourceType()==='document'||/\/api\//.test(u)||/auth|login|logout|profile|users|payments|system|admin|session|2fa|factor|refresh/i.test(u); if(!interesting) return; let keys=[]; const post=req.postData(); if(post){try{keys=Object.keys(JSON.parse(post));}catch{keys=['<non-json-post-body>'];}} const h=res.headers(); result.network.push({label,method:req.method(),status:res.status(),type:req.resourceType(),path:(()=>{try{const uu=new URL(u); return uu.pathname+uu.search}catch{return u}})(),ms:started.has(req)?Date.now()-started.get(req):null,requestKeys:keys,contentType:(h['content-type']||'').split(';')[0],contentLength:h['content-length']||''});}); page.on('console',msg=>{if(['error','warning'].includes(msg.type())) result.console.push({label,type:msg.type(),text:redact(msg.text())});}); page.on('pageerror',err=>result.console.push({label,type:'pageerror',text:redact(err.message||String(err))}));}
async function snap(page,slug,result,extra={}){await page.waitForTimeout(700).catch(()=>{}); const file=path.join(EVID,slug+'.png'); await page.screenshot({path:file,fullPage:true}).catch(e=>result.notes.push('screenshot '+slug+': '+e.message)); const url=sanitizeUrl(page.url()); const title=await page.title().catch(()=> ''); const text=redact(await page.locator('body').innerText({timeout:5000}).catch(()=>'')); const raw=await page.evaluate(()=>({buttons:[...document.querySelectorAll('button,[role="button"]')].map((b,i)=>({i,text:(b.textContent||b.getAttribute('aria-label')||'').trim().slice(0,120),disabled:b.disabled||b.getAttribute('aria-disabled')==='true',aria:b.getAttribute('aria-label'),type:b.getAttribute('type')})).slice(0,220),links:[...document.querySelectorAll('a[href]')].map((a,i)=>({i,text:(a.textContent||'').trim().slice(0,120),href:a.href,target:a.target})).slice(0,220),inputs:[...document.querySelectorAll('input,textarea,select')].map((el,i)=>({i,tag:el.tagName,type:el.getAttribute('type')||el.type,name:el.getAttribute('name'),placeholder:el.getAttribute('placeholder'),id:el.id,valueLength:(el.value||'').length,checked:el.checked})).slice(0,120),active:document.activeElement?`${document.activeElement.tagName}#${document.activeElement.id||''}`:''})).catch(e=>({error:e.message})); const controls={...raw,links:(raw.links||[]).map(l=>({...l,href:sanitizeUrl(l.href)}))}; fs.writeFileSync(path.join(EVID,slug+'.txt'),`URL: ${url}\nTITLE: ${title}\n\n${text}`); result.snapshots.push({slug,file,url,title,controls,...extra}); return {url,title,text,controls};}
async function goto(page,url,slug,result){const rec={slug,requestedUrl:sanitizeUrl(url)}; try{const res=await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000}); rec.status=res?res.status():null; await page.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); const s=await snap(page,slug,result,{httpStatus:rec.status}); rec.finalUrl=s.url; rec.title=s.title; rec.ok=!!res&&rec.status<500;}catch(e){rec.error=e.message; try{await snap(page,slug+'_error',result,{error:e.message});}catch{}} result.steps.push(rec); return rec;}
async function login(page,email,password,slug,result){await page.goto(ADMIN+'/login',{waitUntil:'domcontentloaded',timeout:45000}); await dismiss(page); await page.locator('input[type="email"],input[name="email"]').first().fill(email); await page.locator('input[type="password"],input[name="password"]').first().fill(password); await Promise.allSettled([page.waitForURL(u=>!u.pathname.includes('/login'),{timeout:22000}), page.locator('form').first().getByRole('button',{name:/enter console|sign in|log in/i}).click({timeout:6000})]); await page.waitForLoadState('networkidle',{timeout:12000}).catch(()=>{}); await page.waitForTimeout(1200); const s=await snap(page,slug,result,{account:redact(email),loginOk:!page.url().includes('/login')}); return s;}
async function appLogin(page,email,password,slug,result){await page.goto(APP+'/login',{waitUntil:'domcontentloaded',timeout:45000}); await dismiss(page); await page.locator('input[type="email"],input[name="email"]').first().fill(email); await page.locator('input[type="password"],input[name="password"]').first().fill(password); await Promise.allSettled([page.waitForURL(u=>!u.pathname.includes('/login'),{timeout:18000}), page.locator('form').first().getByRole('button',{name:/sign in/i}).click({timeout:6000})]); await page.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); return await snap(page,slug,result,{account:redact(email),loginOk:!page.url().includes('/login')});}
async function logout(page,result){let clicked=false; for(const action of [async()=>page.getByRole('button',{name:/sign out|logout/i}).first().click({timeout:3000}), async()=>{await page.getByRole('button',{name:/account|admin|operator|menu/i}).first().click({timeout:3000}); await page.getByRole('menuitem',{name:/sign out|logout/i}).first().click({timeout:3000});}, async()=>{await page.locator('button').filter({hasText:/admin|operator|account/i}).first().click({timeout:3000}); await page.locator('button,a').filter({hasText:/sign out|logout/i}).first().click({timeout:3000});}]){try{await action(); clicked=true; break;}catch{}} await page.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await page.waitForTimeout(1500); const s=await snap(page,'admin_after_logout',result,{logoutClicked:clicked}); return {clicked,s};}
(async()=>{const result={prompt:'P18',generatedAt:new Date().toISOString(),steps:[],snapshots:[],network:[],console:[],storage:[],controlInventory:[],bugs:[],blockers:[],securityFindings:[],notes:[]}; const browser=await chromium.launch({ channel: 'chrome', headless: true});
 // Public/anonymous admin entry and deep-link guards.
 const anonCtx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const anon=await anonCtx.newPage(); await attach(anon,'anon',result);
 await goto(anon,ADMIN+'/','admin_root_logged_out',result); await goto(anon,ADMIN+'/login','admin_login_logged_out',result);
 result.controlInventory.push({page:'/login',control:'login fields/remember/sign-in/client portal link/security copy',verdict:'INVENTORIED',evidence:'admin_login_logged_out'});
 for(const r of ['/users','/payments','/system']) await goto(anon,ADMIN+r,`logged_out_deeplink_${r.slice(1)}`,result);
 await anonCtx.close().catch(()=>{});
 // Invalid login probes (spaced, low count).
 const negCtx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const neg=await negCtx.newPage(); await attach(neg,'negative',result);
 await goto(neg,ADMIN+'/login','admin_login_empty_ready',result); try{await neg.locator('form').first().getByRole('button',{name:/enter console|sign in|log in/i}).click({timeout:3000}); await neg.waitForTimeout(1000); await snap(neg,'admin_login_empty_submit_validation',result);}catch(e){result.notes.push('empty submit validation click skipped: '+e.message)}
 await login(neg,ADMIN_EMAIL,'WrongPasswordP18!','admin_invalid_password_once',result);
 const invalidStatus=result.network.filter(n=>n.label==='negative'&&/login|auth/.test(n.path)&&n.method==='POST').map(n=>n.status).pop(); if(invalidStatus===429) result.blockers.push('429 lockout/rate-limit hit after one invalid admin attempt; stopped further invalid admin password retries.');
 await login(neg,CLIENT_EMAIL,PASS,'client_credentials_on_admin',result); await negCtx.close().catch(()=>{});
 // Wrong portal: admin creds on client portal.
 const wrongPortalCtx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const wrongPortal=await wrongPortalCtx.newPage(); await attach(wrongPortal,'wrong_portal',result); await appLogin(wrongPortal,ADMIN_EMAIL,PASS,'admin_credentials_on_client_portal',result); await wrongPortalCtx.close().catch(()=>{});
 // Valid admin login.
 const adminCtx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true,acceptDownloads:true}); const page=await adminCtx.newPage(); await attach(page,'admin',result); const loginSnap=await login(page,ADMIN_EMAIL,PASS,'admin_valid_login_after',result);
 const cookies=await adminCtx.cookies(); result.storage.push({label:'admin_after_login',localStorageKeys:await page.evaluate(()=>Object.keys(localStorage||{})).catch(()=>[]),sessionStorageKeys:await page.evaluate(()=>Object.keys(sessionStorage||{})).catch(()=>[]),cookies:cookies.map(c=>({name:c.name,domain:c.domain,path:c.path,httpOnly:c.httpOnly,secure:c.secure,sameSite:c.sameSite,expires:c.expires?'<set>':'<session>'}))});
 const twofaVisible=/two-factor|2fa|authenticator|verification code|backup code/i.test(loginSnap.text); if(twofaVisible) result.blockers.push('Admin account presented a 2FA challenge, but no admin TOTP/backup-code fixture is available; valid 2FA success not executed.');
 result.controlInventory.push({page:'/login',control:'valid admin sign-in',verdict:page.url().includes('/login')?'CHECK_OR_2FA_CHALLENGE':'PASS',evidence:'admin_valid_login_after'});
 if(!page.url().includes('/login')){
   for(const r of ['/users','/payments','/system']) await goto(page,ADMIN+r,`admin_logged_in_${r.slice(1)}`,result);
   await goto(page,ADMIN+'/','admin_root_logged_in',result);
   // Logout/back/refresh/deep-link
   const lo=await logout(page,result); await page.goBack({waitUntil:'domcontentloaded',timeout:15000}).catch(()=>{}); await snap(page,'admin_back_after_logout',result); await page.reload({waitUntil:'domcontentloaded',timeout:30000}).catch(()=>{}); await page.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await snap(page,'admin_refresh_after_logout',result); await goto(page,ADMIN+'/users','admin_deeplink_after_logout_users',result);
   result.controlInventory.push({page:'admin shell',control:'logout/back/refresh/deep-link guard',verdict:'TESTED',evidence:'admin_after_logout/admin_back_after_logout/admin_refresh_after_logout/admin_deeplink_after_logout_users'});
 }
 await adminCtx.close().catch(()=>{});
 // Refresh-token/session expiry approximation: clear cookies then refresh protected route.
 const expCtx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const exp=await expCtx.newPage(); await attach(exp,'session_expiry',result); await login(exp,ADMIN_EMAIL,PASS,'session_expiry_login',result); if(!exp.url().includes('/login')){await exp.context().clearCookies(); await goto(exp,ADMIN+'/users','session_cleared_users_guard',result);} await expCtx.close().catch(()=>{});
 // Mobile and keyboard.
 const mobCtx=await browser.newContext({viewport:{width:375,height:812},ignoreHTTPSErrors:true}); const mob=await mobCtx.newPage(); await attach(mob,'mobile',result); await goto(mob,ADMIN+'/login','mobile_admin_login_375',result); await mobCtx.close().catch(()=>{});
 const kbCtx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const kb=await kbCtx.newPage(); await attach(kb,'keyboard',result); await goto(kb,ADMIN+'/login','keyboard_admin_login_start',result); for(let i=0;i<10;i++) await kb.keyboard.press('Tab').catch(()=>{}); await snap(kb,'keyboard_admin_login_after_tabs',result); await kbCtx.close().catch(()=>{});
 await browser.close();
 // Security findings and bug derivation.
 const clientAdminText=(result.snapshots.find(s=>s.slug==='client_credentials_on_admin')||{}).controls?'' : '';
 const clientAdminSnap=result.snapshots.find(s=>s.slug==='client_credentials_on_admin'); const clientAdminTxt=fs.existsSync(path.join(EVID,'client_credentials_on_admin.txt'))?fs.readFileSync(path.join(EVID,'client_credentials_on_admin.txt'),'utf8'):'';
 const clientGotAdmin=/Dashboard|Users|Payments|System|Admin/i.test(clientAdminTxt)&&!/Sign in|Invalid|Administrator|operator/i.test(clientAdminTxt);
 if(clientGotAdmin) result.bugs.push({id:'NL-BUG-P18-AUTH-1',severity:'P0',title:'Client credentials gained/admin-rendered privileged shell',evidence:'client_credentials_on_admin'});
 const adminOnClientTxt=fs.existsSync(path.join(EVID,'admin_credentials_on_client_portal.txt'))?fs.readFileSync(path.join(EVID,'admin_credentials_on_client_portal.txt'),'utf8'):'';
 const adminGotClient=/Dashboard|Projects|Quotes|Billing/i.test(adminOnClientTxt)&&!/Administrator accounts cannot|operator/i.test(adminOnClientTxt);
 if(adminGotClient) result.bugs.push({id:'NL-BUG-P18-AUTH-2',severity:'P1',title:'Admin credentials accepted on client portal',evidence:'admin_credentials_on_client_portal'});
 result.securityFindings.push({id:clientGotAdmin?'P18-ROLE-MISMATCH-CLIENT-ADMIN':'P18-ROLE-MISMATCH-CLIENT-ADMIN',severity:clientGotAdmin?'P0':'PASS',surface:'admin login',role:'client credentials on admin portal',impact:clientGotAdmin?'Client reached admin shell':'Client role did not enter admin shell',evidence:'client_credentials_on_admin',fix:clientGotAdmin?'Enforce role check before admin shell bootstrap':'No fix'});
 result.securityFindings.push({id:'P18-ANON-GUARD',severity:'PASS',surface:'admin protected routes',role:'anonymous',impact:'Logged-out deep links guarded by login/from flow',evidence:'logged_out_deeplink_*',fix:'No fix'});
 // Prune login controls from raw for sensitive surface.
 for(const s of result.snapshots){ if(/login/.test(s.slug)) delete s.controls; }
 fs.writeFileSync(path.join(OUT,'p18_result.json'),JSON.stringify(result,null,2));
 const highest=result.bugs.find(b=>b.severity==='P0')?'P0':result.bugs.find(b=>b.severity==='P1')?'P1':result.bugs.find(b=>b.severity==='P2')?'P2':(result.blockers.length?'BLOCKED':'INFO');
 const cov=[['Admin entry','/ and /login logged out','TESTED','admin_root_logged_out / admin_login_logged_out','Gate and login posture captured'],['Invalid/missing login','/login','TESTED_SAFE','admin_login_empty_submit_validation / admin_invalid_password_once','Only one wrong-password attempt to avoid lockout'],['Wrong role','client creds on admin; admin creds on client','TESTED','client_credentials_on_admin / admin_credentials_on_client_portal','Role mismatch checked both directions'],['Logged-out deep links','/users /payments /system','TESTED','logged_out_deeplink_*','from/login guard captured'],['Valid admin login','/login','TESTED','admin_valid_login_after','Admin shell or 2FA challenge captured'],['Protected admin routes','/users /payments /system','TESTED_IF_LOGIN','admin_logged_in_*','Admin routes walked when logged in'],['Logout/back/refresh','logout then back/refresh/deep-link','TESTED_IF_LOGIN','admin_after_logout / admin_back_after_logout / admin_refresh_after_logout','Post-logout shell usability checked'],['Session expiry approximation','clear cookies then /users','TESTED','session_cleared_users_guard','Refresh failure/cookie clear guard'],['Mobile','375px /login','TESTED','mobile_admin_login_375','Mobile login evidence'],['Keyboard','/login tab traversal','TESTED','keyboard_admin_login_after_tabs','Keyboard focus traversal']].map(r=>`| ${r[0]} | ${r[1]} | ${r[2]} | ${r[3]} | ${r[4]} |`).join('\n');
 const controls=result.controlInventory.map(c=>`| ${c.page} | ${c.control} | - | ${c.verdict} | ${c.evidence} |`).join('\n')||'| - | - | - | - | - |';
 const net=result.network.slice(0,240).map(n=>`| ${n.label} | ${n.method} ${n.path} | ${n.status} | ${n.status<400?'OK':'CHECK'} | keys: ${(n.requestKeys||[]).join(', ')}; ${n.contentType||''}; ${n.contentLength||''}; ${n.ms??''}ms |`).join('\n')||'| - | - | - | - | - |';
 const consoleRows=result.console.slice(0,80).map(c=>`| ${c.label} | ${c.type} | ${redact(c.text).replace(/\n/g,' ')} |`).join('\n')||'| - | - | No console warnings/errors captured. |';
 const blockers=result.blockers.map(b=>`- ${redact(b)}`).join('\n')||'- None.';
 const bugText=result.bugs.length?result.bugs.map(b=>`### ${b.id}: ${b.title}\n- Severity: ${b.severity}\n- Evidence: ${b.evidence}`).join('\n\n'):'No confirmed P18 app bugs.';
 const secRows=result.securityFindings.map(f=>`| ${f.id} | ${f.severity} | ${f.surface} | ${f.role} | ${f.impact} | ${f.evidence} | ${f.fix} |`).join('\n');
 const shots=result.snapshots.map(s=>`- ${s.slug}: \`evidence/${path.basename(s.file)}\` — ${s.title} — ${s.url}`).join('\n');
 const md=`# Result — P18 — Admin auth/operator gate, 2FA, role mismatch and session teardown\n\n## Session summary\n- Host/environment: public-domain \`${ADMIN}\` plus client portal \`${APP}\` for wrong-portal check.\n- Browser/MCP/tooling: Playwright Chromium headless, UI-first.\n- Role/account used: seeded admin/operator and seeded client role for mismatch probes.\n- Fixtures created: none.\n- Routes walked: /, /login, /users, /payments, /system, post-logout/deep-link/mobile/keyboard variants.\n- Highest severity: ${highest}\n\n## Coverage table\n| Unit | Route/subsurface | Status | Evidence | Notes |\n|---|---|---|---|---|\n${cov}\n\n## Control inventory deltas\n| Page | Control/tab/dialog | Old-prompt gap? | Runtime verdict | Evidence |\n|---|---|---|---|---|\n${controls}\n\n## Network/API observations\n| Trigger | Method + path | Status | Verdict | Notes |\n|---|---|---:|---|---|\n${net}\n\n## Console findings\n| Context | Type | Message |\n|---|---|---|\n${consoleRows}\n\n## Generated-document/PDF professional integrity\nNot applicable for P18. No Nestlancer-generated PDF/document was produced by the admin-auth/operator-gate flow.\n\n## Blockers / deferred checks\n${blockers}\n\n## Bugs\n${bugText}\n\n## Security findings\n| ID | Severity | Surface | Role | Impact | Evidence | Fix/regression |\n|---|---|---|---|---|---|---|\n${secRows}\n\n## Security checks passed / attempted\n| Area | Sample tested | Verdict | Evidence |\n|---|---|---|---|\n| Anonymous guard | /users /payments /system logged out | PASS | logged_out_deeplink_* |\n| Role mismatch | Client credentials on admin portal | ${clientGotAdmin?'FAIL':'PASS'} | client_credentials_on_admin |\n| Wrong portal | Admin credentials on client portal | ${adminGotClient?'FAIL':'PASS_OR_BLOCKED'} | admin_credentials_on_client_portal |\n| Logout cache | Back/refresh/deep-link after logout | TESTED | admin_after_logout/admin_back_after_logout/admin_refresh_after_logout |\n| Session expiry | Cookies cleared then /users | TESTED | session_cleared_users_guard |\n| Secret hygiene | Token/cookie/password values redacted in report artifacts | PASS_AFTER_SCAN | local scan |\n\n## Handoff\n- Backend/API: continue enforcing admin role at login and protected-route bootstrap; provide a 2FA-enabled admin fixture if operator-gate 2FA success/backup-code paths need deterministic coverage.\n- Frontend/UI: ensure admin shell never flashes privileged widgets before role/session bootstrap completes.\n- Data/setup: avoid repeated invalid admin attempts on shared account; this run used only one invalid-password submission.\n\n## Evidence files\n${shots}\n`;
 fs.writeFileSync(path.join(OUT,'result.md'),md);
})();
