const { chromium } = require('playwright');
const fs=require('fs'), path=require('path'), crypto=require('crypto');
const { execFileSync } = require('child_process');
const OUT='/home/bhumukul-raj/Music/nestlacer-test-output/reports/P03/2fa_attempt'; const EVID=path.join(OUT,'evidence'); fs.mkdirSync(EVID,{recursive:true});
const APP='https://app.nestlancer.com';
const auditPassword='AuditP03TwoFA!'+crypto.randomBytes(4).toString('hex')+'aA1';
const runId=Date.now().toString(36);
function redact(s){return String(s||'').replaceAll(auditPassword,'<redacted-audit-password>').replace(/audit-p03-2fa-[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+/gi,'<audit-2fa-mail>@<mail-domain>').replace(/token=[^\s&"'<>]+/gi,'token=<redacted>').replace(/\b[A-Z2-7]{16,}\b/g,'<redacted-base32-secret>')}
function sanitizeUrl(u){try{const url=new URL(u); for(const k of [...url.searchParams.keys()]) if(/token|secret|code|password|credential|signature|x-amz/i.test(k)) url.searchParams.set(k,'<redacted>'); return url.toString()}catch{return String(u||'')}}
async function mail(){let d=await (await fetch('https://api.mail.tm/domains')).json(); const domain=d['hydra:member'][0].domain; const address=`audit-p03-2fa-${runId}@${domain}`.toLowerCase(); let r=await fetch('https://api.mail.tm/accounts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address,password:auditPassword})}); if(!r.ok&&r.status!==422) throw Error('acct '+r.status+' '+await r.text()); r=await fetch('https://api.mail.tm/token',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address,password:auditPassword})}); let t=await r.json(); return {address,token:t.token,domain}}
async function poll(m, ms=30000){const end=Date.now()+ms; while(Date.now()<end){let r=await fetch('https://api.mail.tm/messages',{headers:{authorization:`Bearer ${m.token}`}}); let j=await r.json(); let msgs=j['hydra:member']||[]; if(msgs[0]){let full=await (await fetch('https://api.mail.tm/messages/'+msgs[0].id,{headers:{authorization:`Bearer ${m.token}`}})).json(); return full;} await new Promise(r=>setTimeout(r,2500));} return null;}
function extract(msg){let src=[msg?.text,msg?.html,msg?.intro].flat().filter(Boolean).join('\n'); let out=[]; for (const m of src.matchAll(/https?:\/\/[^\s"'<>]+/g)){let u=m[0].replace(/&amp;/g,'&').replace(/[\])}.,;]+$/,''); if(/verify-email\?token=/.test(u)) out.push(u)} return [...new Set(out)].sort((a,b)=>b.length-a.length)}
function totp(secret){try{return execFileSync('python3',['-c',`import pyotp; print(pyotp.TOTP(${JSON.stringify(secret)}).now())`],{encoding:'utf8'}).trim()}catch(e){return null}}
async function snap(p,name,extra={}){await p.waitForTimeout(800); await p.screenshot({path:path.join(EVID,name+'.png'),fullPage:true}).catch(()=>{}); const txt=redact(await p.locator('body').innerText().catch(()=>'')); fs.writeFileSync(path.join(EVID,name+'.txt'),`URL ${sanitizeUrl(p.url())}\nTITLE ${await p.title().catch(()=> '')}\n\n${txt}`); return {name,url:sanitizeUrl(p.url()),title:await p.title().catch(()=>''),text:txt,...extra}}
async function dismiss(p){for(const t of ['Accept','Dismiss'])try{const b=p.getByRole('button',{name:t}).first(); if(await b.isVisible({timeout:600})) await b.click()}catch{}}
async function submit(p){try{await p.locator('button[type=submit]').first().click({timeout:3000})}catch{await p.keyboard.press('Enter')}}
(async()=>{
 const result={steps:[],notes:[],blockers:[],address:null,links:[]}; const m=await mail(); result.address=m.address.replace(/^(.{12}).*@/,'$1…@');
 const browser=await chromium.launch({ channel: 'chrome', headless: true}); const ctx=await browser.newContext({viewport:{width:1365,height:900},ignoreHTTPSErrors:true}); const p=await ctx.newPage();
 await p.goto(APP+'/register',{waitUntil:'networkidle'}); await dismiss(p); await p.locator('input[name=firstName]').fill('Audit'); await p.locator('input[name=lastName]').fill('TwoFA'); await p.locator('input[name=email]').fill(m.address); await p.locator('input[name=password]').fill(auditPassword); await p.locator('input[name=confirmPassword]').fill(auditPassword); await p.locator('input[name=acceptTerms]').check(); await submit(p); await p.waitForTimeout(3000); result.steps.push(await snap(p,'register_2fa_user'));
 const msg=await poll(m,30000); if(msg){let links=extract(msg); result.links=links.map(sanitizeUrl); fs.writeFileSync(path.join(EVID,'mail_message_redacted.txt'),redact(`SUBJECT ${msg.subject}\nINTRO ${msg.intro}\nLINKS\n${links.map(sanitizeUrl).join('\n')}`)); for(let i=0;i<links.length;i++){await p.goto(links[i],{waitUntil:'networkidle',timeout:60000}).catch(e=>result.notes.push('verify goto '+e.message)); const s=await snap(p,'verify_link_'+i); result.steps.push(s); if(/verified|success|activated|sign in/i.test(s.text) && !/invalid|expired|couldn't/i.test(s.text)) break;}} else result.blockers.push('No verification email in mail.tm');
 // try login regardless
 await p.goto(APP+'/login',{waitUntil:'networkidle'}); await dismiss(p); await p.locator('input[name=email],input[type=email]').first().fill(m.address); await p.locator('input[name=password],input[type=password]').first().fill(auditPassword); await Promise.allSettled([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:20000}),submit(p)]); await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{}); await p.waitForTimeout(2000); let login=await snap(p,'audit_login_after_verify_attempt'); result.steps.push(login);
 if(new URL(login.url).pathname.includes('/login')) result.blockers.push('Audit account still cannot login after verification attempt'); else {
  await p.goto(APP+'/settings/security',{waitUntil:'networkidle',timeout:60000}); let before=await snap(p,'settings_security_before_2fa'); result.steps.push(before);
  const pwd=p.locator('input[name=twoFactorPassword],#security-2fa-password').first(); if(await pwd.count()){await pwd.fill(auditPassword); await p.getByRole('button',{name:/Start 2FA setup/i}).click().catch(async()=>{await p.locator('button:has-text("Start 2FA setup")').click()}); await p.waitForTimeout(4000); let setup=await snap(p,'twofa_setup_started'); result.steps.push(setup); const raw=await p.evaluate(()=>document.body.innerText+'\n'+[...document.querySelectorAll('img,a,svg,canvas')].map(e=>[e.getAttribute('src'),e.getAttribute('href'),e.getAttribute('alt'),e.getAttribute('data-uri'),e.getAttribute('data-secret')].filter(Boolean).join(' ')).join('\n')).catch(()=> ''); let secret=null; const uri=raw.match(/otpauth:\/\/totp\/[^\s"'<>]+/i); if(uri){try{secret=new URL(uri[0]).searchParams.get('secret')}catch{}} if(!secret){let ms=raw.match(/\b[A-Z2-7]{16,}\b/g)||[]; secret=ms[0]} if(secret){let code=totp(secret); result.notes.push('TOTP secret found and pyotp code generated'); const ci=p.locator('input[name=code],input[name=totpCode],input[placeholder*=code i],input[aria-label*=code i]').first(); if(await ci.count()){await ci.fill('000000'); await p.getByRole('button',{name:/Confirm|Verify|Enable|Continue/i}).click().catch(async()=>{await submit(p)}); await p.waitForTimeout(1500); result.steps.push(await snap(p,'twofa_wrong_code')); if(code){await ci.fill(code); await p.getByRole('button',{name:/Confirm|Verify|Enable|Continue/i}).click().catch(async()=>{await submit(p)}); await p.waitForTimeout(3000); result.steps.push(await snap(p,'twofa_correct_code'));}} else result.blockers.push('Secret found but code input not found');} else result.blockers.push('2FA setup opened but secret not machine-readable from DOM'); } else result.blockers.push('2FA password/start control missing');
 }
 await browser.close(); fs.writeFileSync(path.join(OUT,'result.json'),JSON.stringify(result,null,2)); console.log(JSON.stringify({address:result.address, blockers:result.blockers, notes:result.notes, links:result.links, steps:result.steps.map(s=>({name:s.name,url:s.url,title:s.title,text:s.text.slice(0,120)}))},null,2));
})();
